table '3 Profile Measures'
	lineageTag: fcce49cd-0d5f-4b1f-acb2-c3f7404ca69c

	measure 'Invoiced SmartDrives Off-Chair - USSC' =
			
			// CALCULATE(
			//     SUM('Facts'[Net price]),
			//         FILTER('Facts',
			//         'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			//         'Facts'[Order type] IN {"SMRT", "Parts"} &&
			//         'Facts'[FinProdDesc 1] IN {"Aftermarket", "Manual"} &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Power") &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Services")
			//     )
			// )
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" },
			    -- USSC
			    'Facts'[Order Type - Calculated] IN { "SMRT" },
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    -- expect filter to exclude all Frieght item numbers and RestockExt item numbers typically for restock fees on Returned Orders
			    'Bill to customer'[Bill to internal customer]
			        IN {
			            0
			        } -- using Bill to instead of Ship to as often Returned Orders don't have a Ship to customer number
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 9e365ff6-b7f1-4a28-b206-ae9571f3df6f

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - USSC (excl Freight)' =
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" },
			    -- USSC
			    'Facts'[Order Type - Calculated] IN { "Chair" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    -- expect this to filter out Manual Demos sales which should be added to TiLite
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    -- expect filter to exclude all Frieght item numbers and RestockExt item numbers typically for restock fees on Returned Orders
			    'Bill to customer'[Bill to internal customer]
			        IN {
			            0
			        } -- using Bill to instead of Ship to as often Returned Orders don't have a Ship to customer number
			        -- means any part sold on a Chair Order Type will be measured as Chair for performance
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 64480628-4cc0-4e2a-971e-7376110ea8a9

		changedProperty = FormatString

	measure 'Invoiced Power Parts - USSC' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			        'Facts'[Order type] IN {"Parts"} &&
			        'Facts'[ItemNumber] <> "Freight" &&
			        NOT 'Facts'[Pool Id] IN {"04", "05"}),
			        FILTER('Ship to customer',    
			    'Ship to customer'[Ship to internal customer] IN {0}    ))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: 544dcbe2-65e4-47c0-8c72-cb022296c78b

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off-Chair for Commissions - USSC' =
			
			// CALCULATE(
			//     SUM('Facts'[Net price]),
			//         FILTER('Facts',
			//         'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			//         'Facts'[Initiative] IN {"SmartDrive Commission Identification"} && // Excel file with each part # for sales credit
			//         'Facts'[Order type] IN {"SMRT", "Parts"} &&
			//         'Facts'[FinProdDesc 1] IN {"Aftermarket", "Manual", "Power Assisted Device"} &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Power") &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Services")
			//     )
			// )
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" },-- USSC
			    'Facts'[Initiative] IN {"SmartDrive Commission Identification"}, // Excel file with each part # for sales credit
			    'Facts'[Order Type - Calculated] IN { "SMRT" },
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    -- expect filter to exclude all Frieght item numbers and RestockExt item numbers typically for restock fees on Returned Orders
			    'Bill to customer'[Bill to internal customer]
			        IN {
			            0
			        } -- using Bill to instead of Ship to as often Returned Orders don't have a Ship to customer number
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 0cc283a2-9c27-476e-99f4-a0740e3cfcd9

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off Chair Non-Commissonable - USSC' = ```
			
			    [Invoiced SmartDrives Off-Chair - USSC] - [Invoiced SmartDrives Off-Chair for Commissions - USSC]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: 371da46c-78c5-4da9-8689-80b47ebc95d5

		changedProperty = FormatString

	measure 'Invoiced TiLite On-Chair - SmartDrives Aluminum' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Aluminum",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 0d627ab3-3cb7-4231-a1b1-4d1f26c7ad8d

		changedProperty = FormatString

	measure 'Invoiced TiLite On-Chair - ROHO' =
			
			CALCULATE(
			    SUM('TiLite_AttachmentReporting_Lines'[NetSalesValue]),
			        'TiLite_AttachmentReporting_Lines'[AttachmentType] = "ROHO",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 5c2eac0f-bd8f-4be3-b247-0dfab82c5ec0

		changedProperty = FormatString

	measure 'Invoiced TiLite On-Chair - Comfort' =
			
			CALCULATE(
			    SUM('TiLite_AttachmentReporting_Lines'[NetSalesValue]),
			        'TiLite_AttachmentReporting_Lines'[AttachmentType] = "Comfort Company",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 5ba0bdc0-f2fb-44c2-92f9-61ea2ea76818

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - US Scala' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Power"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" // we don't believe this is filtering anything for Power Chairs
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 23c31364-8d48-4a11-aa77-2ad9da20f3db

		changedProperty = FormatString

	measure 'Invoiced TiLIte Chairs - (Demo) USSC' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" }
			            && // USSC
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 } -- used Bill to as measure is in D365 Fact Table
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 1f8e0045-3ddc-4ab0-8d18-56f7cb6e0aa3

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - US' =
			
			[Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: cf6f0baf-cee6-4dec-b78d-a28530082df2

		changedProperty = FormatString

	measure 'Invoiced Power Parts - Scala US' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Aftermarket"} &&
			        'Facts'[FinProdDesc L12 (Fin Prod)] IN { "Power AM"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" && // we don't believe this is filtering anything for Power Chairs
			    'Ship to customer'[Ship to internal customer] = 0
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 8477c30c-b16c-4197-85a2-cb51adc0ebfe

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off-Chair - US Scala' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Aftermarket", "Manual"} &&
			        'Facts'[FinProdDesc L12 (Fin Prod)] IN { "Manual AM", "Max Mobility"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" // we don't believe this is filtering anything for Power Chairs
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 77fd3b88-d440-4236-bc62-51f0095b003a

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off-Chair for Commissions - Scala US' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Aftermarket", "Manual"} &&
			        'Facts'[FinProdDesc L12 (Fin Prod)] IN { "Manual AM", "Max Mobility"} &&
			        'Facts'[ProductCode] IN { "MS1"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" // we don't believe this is filtering anything for Power Chairs
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 2b425134-4e2c-4f15-8533-52aee66b2dfc

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off Chair Non-Commissionable - Scala US' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Aftermarket", "Manual"} &&
			        'Facts'[FinProdDesc L12 (Fin Prod)] IN { "Manual AM", "Max Mobility"} &&
			        'Facts'[ProductCode] IN { "MX1"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" // we don't believe this is filtering anything for Power Chairs
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: 7cdb621a-4004-4757-98b7-ddf6be6b5a5b

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Off-Chair for Commissions - Total US' = ```
			
			    [Invoiced SmartDrives Off-Chair for Commissions - USSC] + [Invoiced SmartDrives Off-Chair for Commissions - Scala US]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: dac986f7-abe1-4b4f-96bf-3e2a4a313dfc

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced US TiLite Chairs' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - Manual] +
			[Invoiced TiLite Chairs - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 47dbe6ab-ebc9-45d8-ad7c-4a8ff691dc17

		changedProperty = FormatString

	measure 'Invoiced TiLite Parts' =
			
			CALCULATE(
			    SUM('FactCustomerInvoice_UNION'[NetAmount]),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    FILTER('DW DimProduct',
			        'DW DimProduct'[ProductLvl2Name] <> "TiLite"
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: a0d2a87b-b7df-4609-b531-196918edb554

		changedProperty = FormatString

	measure 'Invoiced Power Parts - US' = ```
			
			    [Invoiced Power Parts - USSC] + [Invoiced Power Parts - Scala US]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: 2b355b8a-55cb-41d2-9afc-0c8ab555cf9f

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs excl On Chair SmartDrives' = ```
			
			    [STB Actuals - Total Invoiced US TiLite Chairs] + [Invoiced TiLIte Chairs - (Demo) USSC] - [Invoiced TiLite On-Chair - SmartDrives]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: c7c43df2-0bf4-413d-ab42-6d95bbb0cf11

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - CAN' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			    FILTER('Date',
			        'Date'[date_int] >= 20220401), 
			    FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"} &&
			        'Facts'[Order type] IN {"Chair"} &&
			        'Facts'[FinProdDesc 1] IN {"Aftermarket", "Power"} &&
			        'Facts'[ItemNumber] <> "Freight" &&
			        NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual")),    
			    FILTER('Ship to customer',    
			        'Ship to customer'[Ship to internal customer] IN {0})
			    )
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: ccc19dec-b8dc-4016-8b76-04b4cfff5f6d

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - Scala CAN' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			    FILTER('Facts','Facts'[Date_SK]<=20220331 &&
			    'Facts'[Company_SK]="A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"&&
			    'Facts'[Fact type]="CI LDW" &&
			    'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Power"}),
			    FILTER('Ship to customer','Ship to customer'[Ship to address country region Id] = "CAN"))
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 90d91e5f-33db-4a22-b722-b20ceaa9d96b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Actuals - Total Invoiced US ROHO' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - ROHO] +
			[Total Invoiced ROHO - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 02ca39b1-8ee1-4df7-83a4-fa1c9a3af55e

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced US Comfort' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - Comfort] +
			[Total Invoiced Comfort - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: a3783941-4581-4251-bedc-f4990bb8352a

		changedProperty = FormatString

	measure 'STB PWC' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			//Division of that period's invoiced by the budget for past quarter's STB 
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Power Chairs]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Power Chairs")
			        )
			    )
			
			//Ascertain current quarter's budget
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Power Chairs"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			//Divide amount invoiced so far by current working day of quarter
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Power Chairs], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			//Multiply result of CurrAmountDay by total number of working days in current quarter
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			//Divide result of MultByTotal
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 34fb97e9-dd4b-4a80-92a5-b88a6da29f4a

		changedProperty = FormatString

	measure 'STB Comfort' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Comfort]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Comfort")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Comfort"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Comfort], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 25b14862-4a52-4458-97c7-efc50f00f1f9

		changedProperty = FormatString

	measure 'STB Smart-On Q1' = ```
			
			
			VAR div =
			DIVIDE(
			    CALCULATE([Invoiced TiLite On-Chair - SmartDrives Aluminum], FILTER('Date', 'Date'[Quarter] = 1 && 'date'[year] = 2023)),
			    [Current Working Day - Quarter])
			VAR mult = 
			div * [Total Working Day - Quarter]
			VAR final =
			DIVIDE(
			    mult,
			    CALCULATE([Full Year Budget], 
			    FILTER('Date',
			        'Date'[Quarter] = 1),
			    FILTER('Budget Master',
			        'Budget Master'[Product Line] = "SmartDrive On-Chair")))
			RETURN
			final
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: c937646e-077a-4527-913a-056aa3510c1a

		changedProperty = FormatString

	measure 'STB Smart Off Q1' = ```
			
			VAR div =
			DIVIDE(
			    CALCULATE([Invoiced SmartDrives Off-Chair for Commissions - Total US], FILTER('Date', 'Date'[Quarter] = 1 && 'date'[year] = 2023)),
			    [Current Working Day - Quarter])
			VAR mult = 
			div * [Total Working Day - Quarter]
			VAR final =
			DIVIDE(
			    mult,
			    CALCULATE([Full Year Budget], 
			    FILTER('Date',
			        'Date'[Quarter] = 1),
			    FILTER('Budget Master',
			        'Budget Master'[Product Line] = "SmartDrive Off Chair")))
			RETURN
			final
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 03366ce6-c6a8-440a-8be8-12d11d6ec132

		changedProperty = FormatString

	measure 'STB TiLite' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US TiLite Chairs]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "TiLite")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "TiLite"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US TiLite Chairs], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 015f788e-f41f-4175-b6e1-90162484f4a8

		changedProperty = FormatString

	measure 'STB ROHO' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US ROHO]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "ROHO")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "ROHO"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US ROHO], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 3fa1df07-bd7c-4a5d-9930-ac6533669c66

		changedProperty = FormatString

	measure 'Invoiced Power Parts - CAN' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D", "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B"} && // CAN or Permobil Ltd Canada
			        'Facts'[Order type] IN {"Parts"} &&
			        'Facts'[ItemNumber] <> "Freight" &&
			        NOT 'Facts'[Pool Id] IN {"04", "05"}),
			        FILTER('Ship to customer',    
			    'Ship to customer'[Ship to internal customer] IN {0} &&
			        'Ship to customer'[Ship to address country region Id] = "CAN"))
			```
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 1e83e549-331f-48da-b273-e5a5d5dffde9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) Aluminum - CAN' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Aluminum"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 4eb15548-be14-4352-affe-6eab76924e24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced SmartDrives Off Chair - Total CAN' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"} && // CAN or Permobil Ltd Canada
			        'Facts'[Order type] IN {"SMRT", "Parts"} &&
			        'Facts'[FinProdDesc 1] IN {"Aftermarket", "Manual"} &&
			        NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Power") &&
			        NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Services")
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 57db4e08-7beb-4e77-b8ae-b4142fb25281

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal SmartDrives - CAN' =
			
			[2023 Actuals CAN - SmartDrive] +
			[Total Invoiced CAN SmartDrives - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 747bb16e-1f47-451d-9bdd-45804a0652b6

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced Montreal ROHO - CAN' =
			
			[2023 Actuals CAN - ROHO] +
			[Total Invoiced CAN ROHO - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 00641e54-3884-4290-904b-c9975f12cca3

	measure 'Invoiced Montreal Comfort - CAN' =
			
			[2023 Actuals CAN - Comfort] +
			[Total Invoiced CAN Comfort - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: fab930a6-a911-473f-b2ce-1a93bfc36c20

	measure 'Invoiced Montreal TruShape - CAN' =
			
			[2023 Actuals CAN - TruShape] +
			[Total Invoiced CAN TruShape - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: bc00dca6-48d2-40a3-a55f-ff33f16f5d4b

	measure 'Invoiced Montreal 3rd Party - CAN' =
			
			[2023 Actuals CAN - 3rd Party] +
			[Total Invoiced CAN 3rd Party - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 3bb62a89-890a-46ac-a635-f21e3f1447b7

	measure 'Invoiced TiLite Chairs - US Aluminum' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Aluminum",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 7f32317d-5eff-4d5f-a5f2-728dc5e58912

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - US Titanium' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Titanium",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: b4cfa288-d1ce-4ea8-85fe-08a707f0f234

		changedProperty = FormatString

	measure 'Invoiced TiLIte Chairs - (Demo) Titanium - CAN' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Titanium"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 8a9d22ad-36b1-48a3-8bfc-a0b4f9d8edd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite On-Chair - SmartDrives Titanium' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Titanium",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 1f5d6849-4b97-44c1-b02f-54cee1a59b79

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US Aluminum excl On-Chair SD' = ```
			
			    [Invoiced TiLite Chairs - US Aluminum] - [Invoiced TiLite On-Chair - SmartDrives Aluminum]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 2c9e961e-81ff-43af-b138-0017f34dbc97

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US Titanium excl On-Chair SD' = ```
			
			    [Invoiced TiLite Chairs - US Titanium] - [Invoiced TiLite On-Chair - SmartDrives Titanium]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 5eb0dd07-e718-407e-a93b-1a4fc74ca874

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - CAN' =
			
			CALCULATE(
			SUM('Facts'[Net price]),
			    FILTER('Date',
			        'Date'[date_int] >= 20220401),
			    FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"} &&
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT")))
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 65e424c2-1492-4caa-9f61-2dfcb5dbf4b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal Surfaces - CAN' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Surfaces] = "Surfaces",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 0266d32a-7f33-42bb-8c0a-d6884bead6b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite On-Chair - SmartDrives' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 89302e07-dfae-4c2a-87cf-06636fdb4a72

		changedProperty = FormatString

	measure 'Fact Invoice Recon' =
			
			[STB Actuals - Total Invoiced US Comfort] +
			[Invoiced Montreal SmartDrives - CAN] +
			[STB Actuals - Total Invoiced US ROHO] +
			[STB Actuals - Total Invoiced US TiLite Chairs]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: 0fb292f8-304f-4166-a0f3-9cc7c18c0743

		changedProperty = FormatString

	measure 'Facts Recon' = ```
			
			[STB Actuals - Total Invoiced CAN Power Chairs] +
			[Invoiced Power Parts - US] +
			[Invoiced Power Chairs - CAN] +
			[Invoiced Power Parts - CAN] +
			[Invoiced SmartDrives Off-Chair for Commissions - Total US] + 
			[Invoiced SmartDrives Off Chair - Total CAN] +
			[Invoiced TiLIte Chairs - (Demo) USSC] +
			[Invoiced TiLIte Chairs - (Demo) USSC]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: 6c43e794-ad5c-4904-a685-98e044ae4edb

		changedProperty = FormatString

	measure 'Invoiced Returned Orders - USSC Power Chairs' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       'Facts'[Order type] <> "Chair" &&
			       'Facts'[Order type] <> "Parts" &&
			       'Facts'[Order type]  <> "SMRT" &&
			        'Facts'[FinProdDesc 1] IN {"Power"} &&
			     'Facts'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: f2b6f458-d0da-4b28-94a0-9d8fb176a3fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) USSC Titanium' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" }
			            && // USSC
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Titanium"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 21948b8a-e0db-4f08-bf71-7ebc7e8a3b92

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) USSC Aluminum' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" }
			            && // USSC
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Aluminum"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: ddf1c148-2add-4cfe-a2a2-a7f577842571

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - USSC Power Parts' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT") &&
			       ('Facts'[FinProdDesc 1] IN {"Aftermarket", "Seating & Positioning"}) &&
			       NOT ('Facts'[FinProdDesc 2] IN {"Manual AM"}) &&
			    'Facts'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 3967c256-23ea-4f52-baf8-a5ea1396bbfa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - USSC SmartDrives' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT") &&
			       ('Facts'[FinProdDesc 1] IN {"Manual"}) &&
			    'Facts'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: c5af400f-8b3a-4c73-a32b-1d7b1082ab6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Actuals - Total Invoiced CAN Power Chairs' = ```
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - Power Chair] + 
			[Total Invoiced CAN Power Chairs - Current Period]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: cf1d4e23-2c10-48ff-a02e-88529ee995db

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced US Combined SmartDrives' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - SmartDrive] +
			[Total Combined SmartDrives - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 6585392b-f83c-45a3-8331-43279ee39f1a

		changedProperty = FormatString

	measure 'Fact Invoice ROHO & Comfort' =
			
			[STB Actuals - Total Invoiced US Comfort] +
			[STB Actuals - Total Invoiced US ROHO]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: c831bb08-c8d0-4b7d-82a6-4795df2fcce2

		changedProperty = FormatString

	measure 'STB Smart Combined' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Combined SmartDrives]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "SmartDrive")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "SmartDrive"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US Combined SmartDrives], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: cc5159f8-1071-465a-9ae9-1c8eb86bed02

	measure 'Invoiced Combined SmartDrives' =
			
			[Invoiced SmartDrives Off-Chair for Commissions - Total US] +
			[Invoiced TiLite On-Chair - SmartDrives]
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 98db083f-36bc-408e-ac95-f4b51ac45fed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal' = ```
			
			[Invoiced Montreal 3rd Party - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal SmartDrives - CAN] +
			[Invoiced Montreal Surfaces - CAN] + 
			[Invoiced Montreal TruShape - CAN]
			```
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Power Chairs - CAN' =
			
			[2023 Actuals CAN - Power Chair] +
			[Total Invoiced CAN Power Chairs - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8

	measure 'Total Combined SmartDrives CAN' =
			
			[Invoiced Montreal SmartDrives - CAN Raw] +
			[Invoiced TiLite On-Chair - SmartDrives]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 1ff8f9ec-b70e-4f6b-99ce-73869ded7429

	measure 'STB PWC - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Total Power Chairs - CAN]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Power Chairs")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Power Chairs"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Total Power Chairs - CAN], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2023)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: f0c92aa9-8a43-40bf-a98e-2037eca17bdf

	measure 'STB TiLite - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US TiLite Chairs]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "TiLite"),
			        FILTER('Sales Rep Map',
			            'Sales Rep Map'[Region] = "10")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "TiLite"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY())),
			        FILTER('Sales Rep Map',
			            'Sales Rep Map'[Region] = "10")
			        )
			    )
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced US TiLite Chairs], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 0ec2a21e-e96a-44f1-947c-e9a075efdb4e

	measure 'STB Smart Combined - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced CAN SmartDrives]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "SmartDrive")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "SmartDrive"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([STB Actuals - Total Invoiced CAN SmartDrives], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 39170496-3bd3-407e-91ac-d8d7ce8ebd7b

	measure 'STB ROHO - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Invoiced Montreal ROHO - CAN]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "ROHO")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "ROHO"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Invoiced Montreal ROHO - CAN], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 9ad35877-85bc-4a8e-8df2-7f5813cf491c

	measure 'STB Comfort - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Invoiced Montreal Comfort - CAN]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Comfort")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Comfort"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Invoiced Montreal Comfort - CAN], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2023)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: #,0%;-#,0%;#,0%
		displayFolder: .STB
		lineageTag: 35881c09-6c67-4c9f-a130-1e9d77b36f73

	measure 'Total Canada' =
			
			[Total Power Chairs - CAN] +
			[STB Actuals - Total Invoiced US TiLite Chairs] +
			[Invoiced Combined SmartDrives] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal 3rd Party - CAN]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: fe7d93aa-dff5-48a2-a9b3-d09adce6d31b

	measure 'STB Third Party - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Invoiced Montreal 3rd Party - CAN]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Third Party")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Third Party"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Invoiced Montreal 3rd Party - CAN], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 44eaa5c5-cdb8-4124-8591-ded640665ec9

	measure 'STB Trushape - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Invoiced Montreal TruShape - CAN]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Trushape")
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Trushape"),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Invoiced Montreal TruShape - CAN], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 1a01b484-8be4-427e-bb13-16c6f7fa9ed5

	measure 'Invoiced Returned Orders - USSC Freight' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       'Facts'[Order type] <> "Chair" &&
			       'Facts'[Order type] <> "Parts" &&
			       'Facts'[Order type]  <> "SMRT" &&
			     'Facts'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 927af7b8-a6d7-424b-b7b5-42a3a2184a55

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - USSC SmartDrives Parts' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT") &&
			       ('Facts'[FinProdDesc 2] IN {"Manual AM"}) &&
			    'Facts'[Internal Customer (RO)] IN {0}
			    ))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 149756c2-61db-4440-a3b3-cf4cbf67e078

	measure 'Invoiced Returned Orders - USSC Restock Fees' =
			
			CALCULATE(SUM('Facts'[Net price]),
			FILTER('Facts',
			'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT") &&
			       Isblank(('Facts'[FinProdDesc 1])) &&
			    'Facts'[Internal Customer (RO)] IN {0}
			    ))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 5bc48a6f-820a-41dd-87a4-4184748cd0b0

	measure 'Invoiced TruShape - US' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 109,
			    'DW DimProduct'[ProductLvl2Name] IN { "OBSS", "Trushape" }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 1cd27220-b6f8-4b4a-8aec-4737cfb0c511

		changedProperty = FormatString

	measure 'Invoiced Power S&P On-Chair - ROHO' =
			
			CALCULATE(SUM('Facts_Quote Details'[Net price]),
			FILTER('Facts',
			    'Facts'[Fact type] IN {"SI"} &&
			    'Facts'[Order type] IN {"Chair"}),
			FILTER('Released product',
			    CONTAINSSTRING('Released product'[Product name], "ROHO"))//,
			//    USERELATIONSHIP('Released product'[ReleasedProduct_SK],'Facts_Quote Details'[ReleasedProduct_SK])
			)
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: bff3f99c-d431-4aa8-9f32-cb88eab17af6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Total Canada' =
			
			[Invoiced Power Chairs - Scala CAN] + [Total Power Chairs - CAN] + [Invoiced Power Parts - CAN] + [STB Actuals - Total Invoiced US TiLite Chairs] + [Invoiced TiLite Parts] + [Invoiced Montreal SmartDrives - CAN] + [Invoiced Montreal ROHO - CAN] + [Invoiced Montreal Comfort - CAN] + [Invoiced Montreal 3rd Party - CAN] + [Invoiced Montreal TruShape - CAN]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: c0c01684-ae7e-4ea1-bba9-e7ed44db5d92

	measure 'Invoiced Returned Orders - CAN Final' =
			
			CALCULATE(
			[Invoiced Returned Orders - CAN],
			USERELATIONSHIP('Facts'[Customer_SK],'Ship to customer'[ShipToCustomer_SK]))
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: ad6f1ac3-c011-44f8-89f9-0044b8de5b93

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal Freight- CAN' =
			
			CALCULATE(
			    SUM('FactCustomerInvoice_UNION'[NetAmount]),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			     FILTER('DW DimProduct',
			        'DW DimProduct'[Canada Product] = "Freight"
			   )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: e3eadc4e-963f-4750-964a-39e75d054525

	measure 'Invoiced Power Freight - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    -- CAN or Permobil Ltd Canada
			    'Facts'[ItemNumber] = "Freight",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: bf1bdba1-83c0-42d2-931a-f5ed0cdc0aca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Parts - Scala CAN' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D", "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B"} && // CAN Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Aftermarket"} &&
			        'Facts'[FinProdDesc L12 (Fin Prod)] IN { "Power AM"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] = "CAN" && // we don't believe this is filtering anything for Power Chairs
			    'Ship to customer'[Ship to internal customer] = 0
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: a9551569-dfe4-44e1-986f-2d536bff4313

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB PWC YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			
			VAR CurrAmountDay =
			    CALCULATE([Total Power Chairs - CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2023))
			
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Power Chairs"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Master Budget 2023',
			                'Master Budget 2023'[Product Line] = "Power Chairs"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			
			VAR Result =
			    CurrAmountDay / CurrBudg
			
			RETURN
			    Result
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: f4bed2d0-d16e-48f0-a4ce-0434dcf44ec0

	measure 'STB Total (MAIN) - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Total Canada (MAIN)]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN { "Power Chairs", "SmartDrive", "Comfort", "ROHO", "TiLite Chairs"})
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN { "Power Chairs", "SmartDrive", "Comfort", "ROHO", "TiLite Chairs"}),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Total Canada (MAIN)], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: ef328146-6276-4a90-99b8-15d3191cbedd

	measure 'STB Total (OTHER) - CAN' = ```
			
			
			//PastSTB - Division of that period's invoiced by the budget for past quarter's STB
			//QtrBudg - Ascertain current quarter's budget
			//CurrAmountDay - Divide amount invoiced so far by current working day of quarter
			//MultByTotal - Multiply result of CurrAmountDay by total number of working days in current quarter
			//CurrentSTB - Divide result of MultByTotal
			
			VAR First = 
			    DATE(YEAR(TODAY()), QUARTER(TODAY()), 1)
			
			VAR CurrentQ =
			    QUARTER( ( TODAY () ))
			
			VAR PastSTB =
			DIVIDE(
			    CALCULATE([Total Canada (OTHER)]), 
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN {"Trushape", "Third Party"})
			        )
			    )
			
			VAR QtrBudg =
			CALCULATE(
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN { "Trushape", "Third Party"}),
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			VAR CurrAmountDay =
			DIVIDE(
			    CALCULATE([Total Canada (OTHER)], 
			        FILTER('Date', 
			            'Date'[Quarter] = CurrentQ && 'Date'[year] = 2024)),
			            [Current Working Day - Quarter])
			
			VAR MultByTotal =
			CurrAmountDay * [Total Working Day - Quarter]
			
			VAR CurrentSTB =
			DIVIDE(MultByTotal, QtrBudg)
			
			
			RETURN
			IF(
			    QUARTER(LASTDATE('Date'[Date])) = CurrentQ,
			        CurrentSTB,
			        PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: f6ecde52-b41e-4ad3-8cd6-3cf37e8053f3

	measure 'STB Comfort YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			
			VAR CurrAmountDay =
			    CALCULATE([Invoiced Montreal Comfort - CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2023))
			
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Master Budget 2023',
			            'Master Budget 2023'[Product Line] = "Comfort"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Master Budget 2023',
			                'Master Budget 2023'[Product Line] = "Comfort"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			
			VAR Result =
			    CurrAmountDay / CurrBudg
			
			RETURN
			    Result
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: bbecc5f4-4e1b-4ca5-957d-4741408a3e45

	measure 'STB ROHO YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			
			VAR CurrAmountDay =
			    CALCULATE([Invoiced Montreal ROHO - CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "ROHO"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] = "ROHO"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			
			VAR Result =
			    CurrAmountDay / CurrBudg
			
			RETURN
			    Result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 670d6b7f-7b4a-4953-9ad3-f4e719e6484c

	measure 'STB Smart Combined YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			
			VAR CurrAmountDay =
			    CALCULATE([Total Combined SmartDrives CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "SmartDrive"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] = "SmartDrive"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			
			VAR Result =
			    CurrAmountDay / CurrBudg
			
			RETURN
			    Result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 6f4636f5-22f1-454c-8dbc-a37e2a3b2102

	measure 'STB Third Party YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			VAR CurrAmountDay =
			    CALCULATE([Invoiced Montreal 3rd Party - CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Third Party"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] = "Third Party"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			VAR Result =
			    CurrAmountDay / CurrBudg
			RETURN
			    Result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 29cd29be-1e5f-4730-b48f-4274e0edc337

	measure 'STB TiLite YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			VAR CurrAmountDay =
			    CALCULATE([STB Actuals - Total Invoiced US TiLite Chairs], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "TiLite"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] = "TiLite"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			VAR Result =
			    CurrAmountDay / CurrBudg
			RETURN
			    Result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: e691ecc3-4dd2-4703-89dd-52cf4958300c

	measure 'STB Total (MAIN) YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			VAR CurrAmountDay =
			    CALCULATE([Total Canada (MAIN)], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN { "Power Chairs", "SmartDrive", "Comfort", "ROHO", "TiLite Chairs"}),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] IN { "Power Chairs", "SmartDrive", "Comfort", "ROHO", "TiLite Chairs"}),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			VAR Result =
			    CurrAmountDay / CurrBudg
			RETURN
			    Result
			
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 1b7b7930-1b0b-4d5d-969a-4ccb3648ae1e

	measure 'STB Total (OTHER) YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			VAR CurrAmountDay =
			    CALCULATE([Total Canada (OTHER)], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] IN {"Trushape", "Third Party"}),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] IN {"Trushape", "Third Party"}),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			VAR Result =
			    CurrAmountDay / CurrBudg
			RETURN
			    Result
			
			// RETURN
			// IF(
			//     YEAR(LASTDATE('Date'[Date])) = CurrentY,
			//         CurrentSTB,
			//         PastSTB)
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: b9499296-3f50-47f5-bea2-29667db8a0bb

	measure 'STB Trushape YTD - CAN' = ```
			
			
			VAR CurrentY =
			    YEAR( ( TODAY () ))
			VAR CurrAmountDay =
			    CALCULATE([Invoiced Montreal TruShape - CAN], 
			        FILTER('Date', 
			            'Date'[Year] = CurrentY && 'Date'[year] = 2024))
			VAR QTRBudg =
			    CALCULATE([Full Year Budget],
			        FILTER('Budget Master',
			            'Budget Master'[Product Line] = "Trushape"),
			        FILTER('Date',
			            'Date'[Year] = CurrentY &&
			            'Date'[End of Quarter] < TODAY()))
			VAR CurrQTRBudg =
			    DIVIDE(
			        CALCULATE([Full Year Budget],
			            FILTER('Budget Master',
			                'Budget Master'[Product Line] = "Trushape"),
			            FILTER('Date',
			                'Date'[Year] = CurrentY &&
			                'Date'[Quarter] = QUARTER(TODAY()))),
			        [Total Working Day - Quarter]) * [Current Working Day - Quarter] 
			VAR CurrBudg =
			    QTRBudg + CurrQTRBudg
			VAR Result =
			    CurrAmountDay / CurrBudg
			RETURN
			    Result
			```
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 8ba212e6-3d99-40f6-b4b5-7447700ec075

	measure 'Total Canada (MAIN)' =
			
			[Total Power Chairs - CAN] +
			[STB Actuals - Total Invoiced US TiLite Chairs] +
			[Invoiced Combined SmartDrives] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal Comfort - CAN]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 019191a3-7b5c-4e7e-952b-6919e5585aab

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Canada (OTHER)' =
			
			[Invoiced Montreal TruShape - CAN] +
			[Invoiced Montreal 3rd Party - CAN]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: f3fb8539-5f35-4991-830f-aceedde81390

	measure 'Total Canada (OG)' = ```
			
			[Total Power Chairs - CAN] +
			[STB Actuals - Total Invoiced US TiLite Chairs] +
			[Invoiced Combined SmartDrives] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal TruShape - CAN] + 
			[Invoiced Montreal 3rd Party - CAN]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 5860ecf0-6a29-4ba6-a3fb-339479779ada

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced Power Chairs (excl Freight) - USSC (Orders)' = ```
			
			CALCULATE(
			    SUM('Facts_Sales Orders'[Net price]),
			        FILTER('Facts_Sales Orders',
			        'Facts_Sales Orders'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			        'Facts_Sales Orders'[Order type] IN {"Chair"} &&
			    'Facts_Sales Orders'[FinProdDesc 1] IN {"Aftermarket", "Power"} &&
			    'Facts_Sales Orders'[ItemNumber] <> "Freight" &&
			    NOT CONTAINSSTRING('Facts_Sales Orders'[FinProdDesc 2], "Manual")),    
			    FILTER('Ship to customer',    
			    'Ship to customer'[Ship to internal customer] IN {0}    ))
			```
		displayFolder: Orders
		lineageTag: 5c642bf9-55cd-4a23-9c92-7267ee51b36b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - Scala US (Orders)' =
			
			CALCULATE(
			    SUM('Facts_Sales Orders'[Net price]),
			        FILTER('Facts_Sales Orders',
			        'Facts_Sales Orders'[Date_SK] <= 20220331 &&
			        'Facts_Sales Orders'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts_Sales Orders'[Fact type] = "CI LDW" &&
			        'Facts_Sales Orders'[FinProdDesc L1 (Fin Prod)] IN { "Power"}),
			        FILTER('Ship to customer',
			    'Ship to customer'[Ship to address country region Id] <> "CAN" // we don't believe this is filtering anything for Power Chairs
			    )
			)
		displayFolder: Orders
		lineageTag: ec0b2810-7f20-4a82-abf1-5ec157236e69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US (Orders)' = ```
			
			    [Invoiced Power Chairs (excl Freight) - USSC (Orders)] + [Invoiced Power Chairs - Scala US (Orders)]
			```
		displayFolder: Orders
		lineageTag: 018c6ddb-1f8d-4f4b-8fa0-395eace15fdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - USSC Power Chairs (Orders)' =
			
			CALCULATE(SUM('Facts_Sales Orders'[Net price]),
			FILTER('Facts_Sales Orders',
			'Facts_Sales Orders'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			       'Facts_Sales Orders'[Order type] <> "Chair" &&
			       'Facts_Sales Orders'[Order type] <> "Parts" &&
			       'Facts_Sales Orders'[Order type]  <> "SMRT" &&
			        'Facts_Sales Orders'[FinProdDesc 1] IN {"Power"} &&
			     'Facts_Sales Orders'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: Orders
		lineageTag: dfb7c90a-a45e-496b-9648-1cdcab062dc9

	measure 'Total Power Chairs (Orders)' = ```
			
			[Invoiced Power Chairs - US (Orders)] + 
			[Invoiced Returned Orders - USSC Power Chairs (Orders)]
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Orders
		lineageTag: fd1958d4-c2da-44fb-835f-e5b9cf880394

	measure 'TiLite Bookings' = ```
			
			CALCULATE(
			    SUMX('DASH_BOOKINGS_TILITECHAIRONLY', 
				'DASH_BOOKINGS_TILITECHAIRONLY'[NET]))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Orders
		lineageTag: 5b83be6e-df47-4f6b-b4bf-331cf937a514

	measure 'Off-Chair SmartDrive Bookings' =
			
			CALCULATE(
			   SUM('Facts_Sales Orders'[Net price]),
			      'Company'[Company] = "USSC",
			      'Facts_Sales Orders'[RecordSource] = "SO",
			      'Facts_Sales Orders'[Order type] = "SMRT",
			      FILTER(
			         'Released product',
			         LEFT('Released product'[Product name],22) = "Smartdrive MX2+ System"
			      )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Orders
		lineageTag: cc9cf57f-a80d-4b08-876e-8dd26181f970

	measure 'On-Chair SmartDrive Bookings' =
			
			CALCULATE(
			    SUM('DASH_BOOKINGS_MAX'[NET])
			)
		displayFolder: Orders
		lineageTag: 464fd864-11fc-4916-8103-473f0bb3ed34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Combined Smartdrive Bookings' =
			
			[Off-Chair SmartDrive Bookings] + [On-Chair SmartDrive Bookings]
		displayFolder: Orders
		lineageTag: d049ce2a-a099-4d6c-854f-be5356651e35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ROHO Bookings' =
			
			CALCULATE(
			    SUM('All S&P Orders'[NetAmount]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Orders
		lineageTag: 6b39b214-0ab4-4e92-bb4c-99909e4e87c9

	measure 'Invoiced Montreal for Dealer Rebates' =
			
			[Invoiced Montreal 3rd Party - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal SmartDrives - CAN] +
			[Invoiced Montreal TruShape - CAN]
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: b3ede489-40c2-442e-8bff-4de6ca9a6929

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Price Growth YoY PPY' =
			
			IF([Invoiced Power Chairs - US 2022] > 0 && [Invoiced Power Chairs - US 2021] > 0,
			    DIVIDE(
			        ([Invoiced Power Chairs - US 2022] - [Invoiced Power Chairs - US 2021]),
			        [Invoiced Power Chairs - US 2021]), BLANK())
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 9d5e9307-d1ae-4716-828d-209e835864df

		changedProperty = FormatString

	measure '% Sales Growth YTD' = ```
			
			VAR PrevYTD =
			CALCULATE([Invoiced Power Chairs - US 2022 NSM],
			    'Date'[YTD] = "YTD" && 'Date'[PY])
			RETURN
			IF([Invoiced Power Chairs - US 2023 NSM] > 0 && 
			    [Invoiced Power Chairs - US 2022 NSM] > 0,
			    DIVIDE([Invoiced Power Chairs - US 2023 NSM] - [Invoiced Power Chairs - US 2022 NSM],
			        [Invoiced Power Chairs - US 2022 NSM]), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 73b48b4c-15e3-44e7-a3b1-0a55f4191c9a

		changedProperty = FormatString

	measure '% Unit Growth YoY PPY' = ```
			
			IF([Invoiced Power Chairs - US 2022 (NSM Units)] > 0 && [Invoiced Power Chairs - US 2021 (Units)] > 0,
			    DIVIDE(
			        ([Invoiced Power Chairs - US 2022 (NSM Units)] - [Invoiced Power Chairs - US 2021 (Units)]),
			        [Invoiced Power Chairs - US 2021 (Units)]), BLANK())
			
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 5d8c5aac-7e59-42d0-97c2-8ae07a5fb020

		changedProperty = FormatString

	measure '% Units Growth YTD' = ```
			
			IF([Invoiced Power Chairs - US 2023 (Units)] > 0 && [Invoiced Power Chairs - US 2022 (NSM Units)] > 0,
			    DIVIDE([Invoiced Power Chairs - US 2023 (Units)] - [Invoiced Power Chairs - US 2022 (NSM Units)], 
			        [Invoiced Power Chairs - US 2022 (NSM Units)]), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 7adcd3ca-b2b8-4290-878c-1348f24674c9

		changedProperty = FormatString

	measure 'Price 2021 Inv' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        'Facts'[IBQ #'s] = 1,
			        DATESBETWEEN('Date'[Date], MIN('Date'[PPY]), MAX('Date'[PPY])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: 73282bbf-a828-407e-9d6d-1dc049a3d64e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Price 2022 Inv' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        'Facts'[IBQ #'s] = 1,
			        DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: 83b95565-17e7-4010-ae0d-fbdef5301d45

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Price 2023 Inv' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        'Facts'[IBQ #'s] = 1,
			        DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .z All Other
		lineageTag: d8ad1de9-57c5-4d93-b768-6e2e9717244f

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Units- Invoice 2021' =
			
			DIVIDE(
			    CALCULATE(
			        SUM(Facts[IBQ #'s]),
			            DATESBETWEEN('Date'[Date], MIN('Date'[PPY]), MAX('Date'[PPY])),
			            'Facts'[Order type] = "chair",
			            Facts[IBQ #'s] = 1),
			            1)
		formatString: #,0
		displayFolder: .z All Other
		lineageTag: 39048945-db7d-4abf-80d9-0d9100e08c1a

		changedProperty = FormatString

	measure 'Units- Invoice 2022' = ```
			
			// DIVIDE(
			//     CALCULATE(
			//         SUM(Facts[IBQ #'s]), 
			//             DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])),
			//             'Facts'[Order type] = "chair",
			//             Facts[IBQ #'s] = 1),
			//             1)
			CALCULATE(SUM('Facts'[IBQ #'s]),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		formatString: #,0
		displayFolder: .z All Other
		lineageTag: 80f965ce-4190-49ba-b9dd-e2eca17c830a

		changedProperty = FormatString

	measure 'Units- Invoice 2023' = ```
			
			DIVIDE(
			    CALCULATE(
			        SUM(Facts[IBQ #'s]), 
			            DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			            'Facts'[Order type] = "chair",
			            Facts[IBQ #'s] = 1),
			            1)
			```
		formatString: 0
		displayFolder: .z All Other
		lineageTag: 19636f68-330e-4395-a828-e3162ba4749b

		changedProperty = FormatString

	measure 'Dolls Diff Top' = ```
			
			VAR top10 =
			RANKX(ALL('Ship to customer'[ProfileCustomerName]), 
			    CALCULATE([Price 2023 Inv]-[Price 2022 Inv]),,DESC,Dense)
			
			VAR bot10 =
			RANKX(ALL('Ship to customer'[ProfileCustomerName]), 
			    CALCULATE([Price 2023 Inv]-[Price 2022 Inv]),,ASC,Dense)
			
			RETURN
			IF(top10 <= 13, CALCULATE([Price 2023 Inv]-[Price 2022 Inv]), BLANK())
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 703dcbe1-9c4a-46d1-bd9e-ecc1683f7c65

	measure 'Dolls Diff Bottom' =
			
			VAR top10 =
			RANKX(ALL('Ship to customer'[ProfileCustomerName]), CALCULATE([Price 2023 Inv]-[Price 2022 Inv]),,DESC,Dense)
			
			VAR bot10 =
			RANKX(ALL('Ship to customer'[ProfileCustomerName]), CALCULATE([Price 2023 Inv]-[Price 2022 Inv]),,ASC,Dense)
			
			RETURN
			IF(bot10 <= 10, CALCULATE([Price 2023 Inv]-[Price 2022 Inv]), BLANK())
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 014b2852-b534-4e0c-a3ad-392f12a6d7cd

	measure 'Invoiced Power Chairs - US 2023' =
			
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])))
		displayFolder: Provider Measures
		lineageTag: bb79e350-0604-4a70-98a5-89dfc508c8fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs (excl Freight) - USSC (Units)' = ```
			
			CALCULATE(
			    SUM('Facts'[NoChairs]),
			        FILTER('Date',
			            'Date'[date_int] > 20220331),
			        FILTER('Facts',
			        'Facts'[ItemNumber] <> "Freight" &&
			        'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			        ('Facts'[Order type] = {"Chair"} || 
			        ISBLANK('Facts'[Order type])) &&
			    NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual")))
			```
		formatString: 0
		displayFolder: Provider Measures
		lineageTag: 8b876da8-a07b-4763-88e1-b60fa79095f4

	measure 'Invoiced Power Chairs - Scala US (Units)' =
			
			CALCULATE(
			    COUNT('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Date_SK] <= 20220331 &&
			        'Facts'[Company_SK] = "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B" && // US Company (Scala only used US for all transactions)
			        'Facts'[Fact type] = "CI LDW" &&
			        'Facts'[FinProdDesc L1 (Fin Prod)] IN { "Power"} &&
			        'Facts'[ItemNumber] <> "Freight"),
			        FILTER('Ship to customer',
			            'Ship to customer'[Ship to address country region Id] <> "CAN") // we don't believe this is filtering anything for Power Chairs
			    )
		displayFolder: Provider Measures
		lineageTag: c4d1c345-c7fd-40df-af7f-cf4e31fb031d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 (Units)' =
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs (excl Freight) - USSC (Units)],
			        'Ship to customer'[MasterCompanyChain] = "NSM"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    FILTER('Date',
			        'Date'[YTD] = "YTD"))
		formatString: 0
		displayFolder: Provider Measures
		lineageTag: bab25df9-fb09-4a0e-8f7b-be257e235dfa

	measure 'Invoiced Power Chairs - US 2022' =
			
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 7a8e2f15-4b75-44d1-b15c-c7ecdcc89e8d

	measure 'Invoiced Power Chairs - US 2022 (NSM Units)' = ```
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs (excl Freight) - USSC (Units)],
			        'Bill to customer'[Bill to company chain] = "NSM") + 
			    CALCULATE([Invoiced Power Chairs - Scala US (Units)],
			        'Ship to customer'[MasterCompanyChain] = "NSM"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		formatString: #,0
		displayFolder: Provider Measures
		lineageTag: dc47bdad-5935-4616-b7ab-e6639782cd56

	measure 'Invoiced Power Chairs - US 2021' =
			
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    DATESBETWEEN('Date'[Date], MIN('Date'[PPY]), MAX('Date'[PPY])))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 94517646-59ba-4b56-b6a3-181b06385c0d

	measure 'Invoiced Power Chairs - US 2021 (Units)' =
			
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (Units)] + [Invoiced Power Chairs - Scala US (Units)],
			    DATESBETWEEN('Date'[Date], MIN('Date'[PPY]), MAX('Date'[PPY])))
		formatString: #,0
		displayFolder: Provider Measures
		lineageTag: 39e867d4-d878-41df-bccf-3d2fe9bb66a2

	measure 'Invoiced Power Parts - US PY' = ```
			
			CALCULATE(
			    [Invoiced Power Parts - USSC] + [Invoiced Power Parts - Scala US],
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			
			
			```
		displayFolder: Provider Measures
		lineageTag: 4f315b37-e817-47fa-a8b9-61c784d6d3cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Parts - US CY' =
			
			CALCULATE(
			    [Invoiced Power Parts - USSC] + [Invoiced Power Parts - Scala US],
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])))
		displayFolder: Provider Measures
		lineageTag: 7ce5960c-8b45-41ed-acac-2a510542467d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 (NSM)' =
			
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    FILTER('Ship to customer',
			        'Ship to customer'[MasterCompanyChain (groups)] = "NSM"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    FILTER('Date',
			        'Date'[Year] = 2023))
		displayFolder: .z All Other
		lineageTag: c073b369-3528-46b1-84a4-4abdad1c8d78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 (USM)' =
			
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    FILTER('Ship to customer',
			        'Ship to customer'[MasterCompanyChain (groups)] = "USM"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    FILTER('Date',
			        'Date'[Year] = 2023))
		displayFolder: .z All Other
		lineageTag: 1c3d4254-df70-4911-bb15-5b2a7bbecefc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 (Other)' =
			
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    FILTER('Ship to customer',
			        'Ship to customer'[MasterCompanyChain (groups)] = "Other"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    FILTER('Date',
			        'Date'[Year] = 2023))
		displayFolder: .z All Other
		lineageTag: 7c881789-9d1a-4c2b-9c6c-434aebc7f69f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs (excl Freight) - USSC (NSM)' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			        ('Facts'[Order type] = {"Chair"} || 
			        ISBLANK('Facts'[Order type])) &&
			        'Facts'[ItemNumber] <> "Freight" &&
			    NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual")))
			```
		displayFolder: .z All Other
		lineageTag: 8fc5fd5e-deee-4b02-88bb-177cb01029ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - Scala US (NSM)' =
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			            'Facts'[Order Type Q1 Fix] = "chair" &&
			            'Facts'[Fact type] = "CI LDW" &&
			            'Facts'[CustomerCChain] = "NSM" &&
			            'Facts'[ItemNumber] <> "Freight" &&
			            'Facts'[Product Name] <> BLANK()))
		displayFolder: .z All Other
		lineageTag: f52d11d4-3746-418a-b969-58763684dbe9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 NSM' =
			
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    'Date'[YTD] = "YTD")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 43177a85-fc8e-4d44-82b9-8dde0996bd17

	measure 'Invoiced Power Chairs - US 2022 NSM' = ```
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs (excl Freight) - USSC (NSM)],
			        'Bill to customer'[Bill to company chain] = "NSM") + 
			    CALCULATE([Invoiced Power Chairs - Scala US (NSM)],
			        'Ship to customer'[MasterCompanyChain] = "NSM"),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures
		lineageTag: 49914385-13f4-4094-8b4c-8af117df4a34

	measure 'Invoiced Power Chairs - Scala US (NSM Units)' =
			
			CALCULATE(
			    SUM('Facts'[NoChairs]),
			        FILTER('Facts',
			            'Facts'[Order Type Q1 Fix] = "chair" &&
			            'Facts'[Fact type] = "CI LDW" &&
			            'Facts'[CustomerCChain] = "NSM" &&
			            'Facts'[ItemNumber] <> "Freight" &&
			            'Facts'[Product Name] <> BLANK()))
		displayFolder: Provider Measures
		lineageTag: 15c5f773-13ce-44a5-ae52-14fe09ee1a23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 NSM PrevMonth' =
			
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			RETURN
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    'Date'[Month] = PrevMonth,
			    'Date'[Year] = 2023)
		displayFolder: Provider Measures
		lineageTag: 0dfa3d4a-6394-4ad4-83a9-14b4bd986b14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 NSM CurrMonth' =
			
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			RETURN
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    'Date'[Month] = CurrMonth,
			    'Date'[Year] = 2023)
		displayFolder: Provider Measures
		lineageTag: cddf8659-d5a0-4e3b-b0c9-2e9fe89d4078

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 NSM PrevMonth - 1' =
			
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth2 = IF(CurrMonth = 1, 12, CurrMonth - 2)
			RETURN
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    'Date'[Month] = PrevMonth2,
			    'Date'[Year] = 2023)
		displayFolder: Provider Measures
		lineageTag: 12d8c08e-326f-4303-a74b-bc79c13b2868

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - US 2023 NSM PrevMonth - 2' =
			
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth3 = IF(CurrMonth = 1, 12, CurrMonth - 3)
			RETURN
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    'Date'[Month] = PrevMonth3,
			    'Date'[Year] = 2023)
		displayFolder: Provider Measures
		lineageTag: 5a8a5e0f-0e1f-4915-8800-6c25af7542bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs CurrMonth Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = CurrMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = CurrMonth,
			    'Date'[Year] = PrevYr)
			
			RETURN
			IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq)
			        , BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: e7fe9206-7381-463b-9be3-75d6300a603b

	measure 'Invoiced Power Chairs PrevMonth Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: f60b8c5a-5c97-4240-8208-deaff8ffc268

	measure 'Invoiced Power Chairs PPrevMonth Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PPrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 2)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PPrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PPrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 3babe671-1ca2-4688-a351-ad0bb3263f0f

	measure 'Invoiced Power Chairs PPPrevMonth Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PPPrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 3)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PPPrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs (excl Freight) - USSC (NSM)] + [Invoiced Power Chairs - Scala US (NSM)],
			    'Bill to customer'[Bill to company chain] = "NSM",
			    ALL('Date'),
			    'Date'[Month] = PPPrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: b2378a3e-8bf8-4566-b741-378329d07f6d

	measure '% Sales Growth MTD' = ```
			
			VAR PrevYTD =
			CALCULATE([Invoiced Power Chairs - US 2022 NSM],
			    'Date'[YTD] = "YTD" && 'Date'[PY])
			RETURN
			CALCULATE(
			IF([Invoiced Power Chairs - US 2023 NSM] > 0 && 
			    [Invoiced Power Chairs - US 2022 NSM] > 0,
			    DIVIDE([Invoiced Power Chairs - US 2023 NSM] - [Invoiced Power Chairs - US 2022 NSM],
			        [Invoiced Power Chairs - US 2022 NSM]), BLANK()),
			        'Date'[Month] = MONTH(TODAY()))
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 540d6d09-b064-40a7-9d98-db5aa5034dfc

	measure Quoted = ```
			
			// CALCULATE(
			//     SUM('QuotesTEST'[Chairs])
			//     )
			
			CALCULATE(
			    SUM(LegacyQuotesTEST[Quote_Count]))
			    + 
			CALCULATE(
			    SUM('QuotesTEST'[Chairs]),
			        'QuotesTEST'[Quote_Date_Key] > DATE(2022, 03, 31))
			```
		formatString: 0
		displayFolder: .z All Other
		lineageTag: 099295f7-209e-467d-8c62-e6703719d3d2

	measure 'Quoted PY' = ```
			
			CALCULATE(
			    SUM(LegacyQuotesTEST[Quote_Count]),
			        DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY]))
			        ) + 
			CALCULATE(
			    SUM('QuotesTEST'[Chairs]),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		displayFolder: .z All Other
		lineageTag: 36bc30c2-3339-4cef-9ba1-90468ba9620c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quoted YoY Change' =
			
			IF([Quoted PY MTD] > 0,
			    DIVIDE(
			        [Quoted MTD],
			        [Quoted PY MTD]) - 1, BLANK())
		formatString: 0%;-0%;0%
		displayFolder: .z All Other
		lineageTag: 4348836f-fcc1-4691-907d-c3538819a11c

	measure 'Invoiced TiLite Chairs - Titanium (excl On-Chair SmartDrives) - Use Relationship' =
			
			[Invoiced TiLite Chairs - US Titanium] - [Invoiced TiLite On-Chair - SmartDrives Titanium (UR_CM)]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 46441dbb-83a6-41ae-a5cd-8cb1fd575ff2

	measure 'Invoiced TiLite Chairs - Aluminum (excl On-Chair SmartDrives) - Use Relationship' =
			
			[Invoiced TiLite Chairs - US Aluminum] - [Invoiced TiLite On-Chair - SmartDrives Aluminum (UR_CM)]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 5a5a9a42-df34-4ac9-8a4f-a2be21bebf48

	measure 'Invoiced TiLite On-Chair - SmartDrives Aluminum (UR_CM)' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Aluminum",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: 0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 6688fa0a-9da1-483e-a9c0-d68613f92d2b

	measure 'Invoiced TiLite On-Chair - SmartDrives Titanium (UR_CM)' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Titanium",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: 0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: cb8ed345-53be-4c87-b734-e3a381f7a2d3

	measure 'Invoiced TiLite On-Chair - SmartDrives (UR)' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 8fd18d9b-fb0b-4961-9244-59f33244cfec

	measure 'Total Canada Commissions for Reps' =
			
			[Total Power Chairs - CAN] +
			[Invoiced Power Parts - CAN (Thin)] +
			[Invoiced TiLite Chairs - Titanium (excl On-Chair SmartDrives) - Use Relationship] +
			[Invoiced TiLite Chairs - Aluminum (excl On-Chair SmartDrives) - Use Relationship] +
			[Invoiced TiLite On-Chair - SmartDrives (UR)] +
			[Invoiced Montreal SmartDrives - CAN] +
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal Comfort (Vicair) - CAN] +
			[Invoiced Montreal TruShape - CAN] +
			[Invoiced Montreal 3rd Party - CAN (excl Vicair)]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .z All Other
		lineageTag: 2b34438a-576d-4ceb-ac03-089752ea8596

	measure 'Total Canada Commissions for Reps (BH)' =
			
			[Invoiced Montreal ROHO - CAN] +
			[Invoiced Montreal Comfort - CAN] +
			[Invoiced Montreal Comfort (Vicair) - CAN] +
			[Invoiced Montreal TruShape - CAN] +
			[Invoiced Montreal 3rd Party - CAN (excl Vicair)]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .z All Other
		lineageTag: 83fbf121-4134-418c-ba24-17e3cba7e9c4

	measure 'Invoiced Montreal Comfort (Vicair) - CAN' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "3rd Party",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 },
			    'DW DimProduct'[ProductCode] IN { "VIC", "VICM" }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 3ecfff71-f672-4d64-8d29-b6e7529c0b8a

	measure 'Invoiced Montreal 3rd Party - CAN (excl Vicair)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "3rd Party",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 },
			    NOT 'DW DimProduct'[ProductCode] IN { "VIC", "VICM" }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 55d74892-6f01-4456-bd6f-b9897cf7bdc4

	measure 'Invoiced Power Parts - CAN (Thin)' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D", "B473A5ECB9EEEBFCB444E0D4B4269A1E0E33740B"} && // CAN or Permobil Ltd Canada
			        'Facts'[Order type] IN {"Parts"} &&
			        'Facts'[ItemNumber] <> "Freight" &&
			        NOT 'Facts'[Pool Id] IN {"04", "05"}),
			        FILTER('Ship to customer',    
			    'Ship to customer'[Ship to internal customer] IN {0} &&
			        'Ship to customer'[Ship to address country region Id] = "CAN"))
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: d02b2377-f29f-4873-b6b9-95b9611c5532

	measure 'Quoted MTD' =
			
			IF (TOTALMTD([Quoted],DATESMTD('date'[date])) = BLANK(), 0, TOTALMTD([Quoted],DATESMTD('date'[date])))
		formatString: #,0
		displayFolder: .z All Other
		lineageTag: 80550e5d-45e4-4daa-ad59-216772585ebc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Quoted PY MTD' = ```
			
			SWITCH(
			    TRUE(), 
			    VALUE(SELECTEDVALUE('Date'[Year])) = YEAR(TODAY()) && VALUE(SELECTEDVALUE('Date'[yyyymm])) = month(TODAY()),
			    CALCULATE([Quoted], 
			        FILTER(ALL('Date'),'Date'[MTD] = "MTD")),
			    CALCULATE(TOTALMTD([Quoted],
			        SAMEPERIODLASTYEAR('Date'[Date])))
			)
			```
		displayFolder: .z All Other
		lineageTag: cff9d560-4765-4e82-93ac-cacf902a896d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Sales Growth YTD copy' = ```
			
			VAR PrevYTD =
			CALCULATE([Invoiced Power Chairs - US 2022 NSM],
			    'Date'[YTD] = "YTD" && 'Date'[PY])
			RETURN
			IF([Invoiced Power Chairs - US 2023 NSM] > 0 && 
			    [Invoiced Power Chairs - US 2022 NSM] > 0,
			    DIVIDE([Invoiced Power Chairs - US 2023 NSM] - [Invoiced Power Chairs - US 2022 NSM],
			        [Invoiced Power Chairs - US 2022 NSM]), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 833459eb-61a1-44f7-9db9-b87b55dd3960

		changedProperty = FormatString

	measure '% Sales Growth MTD copy' = ```
			
			VAR PrevYTD =
			CALCULATE([Invoiced Power Chairs - US 2022 NSM],
			    'Date'[YTD] = "YTD" && 'Date'[PY])
			RETURN
			CALCULATE(
			IF([Invoiced Power Chairs - US 2023 NSM] > 0 && 
			    [Invoiced Power Chairs - US 2022 NSM] > 0,
			    DIVIDE([Invoiced Power Chairs - US 2023 NSM] - [Invoiced Power Chairs - US 2022 NSM],
			        [Invoiced Power Chairs - US 2022 NSM]), BLANK()),
			        'Date'[Month] = MONTH(TODAY()))
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures
		lineageTag: 7da830f9-42cc-4dab-9c3f-58b7a9f76452

	measure 'Heat Map - US 2022 Units' = ```
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs (excl Freight) - USSC (Units)]) + 
			    CALCULATE([Invoiced Power Chairs - Scala US (Units)]),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		formatString: #,0
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 5dde10ed-da09-4fb5-8508-dff45d3c3310

	measure 'Heat Map - US 2022 Sales' = ```
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs - USSC (excl Freight)]) + 
			    CALCULATE([Invoiced Power Chairs - US Scala]),
			    DATESBETWEEN('Date'[Date], MIN('Date'[PY]), MAX('Date'[PY])))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 0c40200a-6047-4548-877e-ef91ae688cef

	measure 'Heat Map - US 2023 Units' =
			
			CALCULATE(
			    CALCULATE([Invoiced Power Chairs (excl Freight) - USSC (Units)]),
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    FILTER('Date',
			        'Date'[YTD] = "YTD"))
		formatString: 0
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 042b7061-88f4-4654-b194-4f3cd90b0f95

	measure 'Heat Map - US 2023 Sales' =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)],
			    DATESBETWEEN('Date'[Date], MIN('Date'[Date]), MAX('Date'[Date])),
			    'Date'[YTD] = "YTD")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 72580409-f70c-40c8-87ad-38d71b7ca674

	measure 'Heat Map 0 Month Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = CurrMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = CurrMonth,
			    'Date'[Year] = PrevYr)
			
			RETURN
			IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq)
			        , BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 7e61e475-b1e0-4c14-be21-594aab3812c9

	measure 'Heat Map -1 Month Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 1)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 6ff0a88b-4dd1-4c5f-afce-0fe6c6039700

	measure 'Heat Map -2 Month Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PPrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 2)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PPrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PPrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: 14081736-c3aa-4022-b6ad-9215d117443a

	measure 'Heat Map -3 Month Growth %' = ```
			
			VAR CurrYr = YEAR(TODAY())
			VAR PrevYr = CurrYr - 1
			VAR CurrMonth =  MONTH(TODAY())
			VAR PPPrevMonth = IF(CurrMonth = 1, 12, CurrMonth - 3)
			VAR CurrYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PPPrevMonth,
			    'Date'[Year] = CurrYr)
			VAR PrevYrEq =
			CALCULATE(
			    [Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala],
			    ALL('Date'),
			    'Date'[Month] = PPPrevMonth,
			    'Date'[Year] = PrevYr)
			RETURN
			 IF(CurrYrEq > 0 && PrevYrEq > 0,
			    DIVIDE(CurrYrEq - PrevYrEq, 
			        PrevYrEq), BLANK())
			```
		formatString: 0%;-0%;0%
		displayFolder: Provider Measures\Heat Map Measures
		lineageTag: e55e5818-45c4-4aca-a2ab-298e58df18f8

	measure 'Quoted (Open)' =
			
			VAR hist =
			CALCULATE(
			    COUNTROWS('Open Quotes PWC - Historical'),
			    LASTDATE('Open Quotes PWC - Historical'[Date Key]),
			    'Date'[Date] <= date(2022,03,31))
			VAR histnew =
			CALCULATE(
			    COUNTROWS('Open Quotes PWC - Historical (new)'),
			    'Open Quotes PWC - Historical (new)'[OrderStatus] <> 4,
			    LASTDATE('Open Quotes PWC - Historical (new)'[Date Key]),
			        'Date'[Date] > date(2022,03,31))
			RETURN
			hist + histnew
		displayFolder: .z All Other
		lineageTag: 5a94919b-cd92-4a16-899e-674682b00af7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quoted (AVG Conversion Days)' = ```
			
			CALCULATE(
			    AVERAGE('LegacyQuotesTEST'[Conversion Days (adj outlier)]),
			    USERELATIONSHIP('Date'[Date], 'LegacyQuotesTEST'[Order Date Key])) 
			    +
			CALCULATE(
			    AVERAGE('QuotesTEST'[Conversion Days (adj outlier)]),
			        NOT(ISBLANK('QuotesTEST'[OrderNumber])),
			        USERELATIONSHIP('Date'[Date], 'QuotesTEST'[Order date]))
			```
		formatString: 0.0
		displayFolder: .z All Other
		lineageTag: 453e764e-a635-4612-bf7d-2cfcfd5b8801

	measure 'Quoted (Open) PY' = ```
			
			
			var lastdateAvailable=
			CALCULATE(MAX(
			    'Facts'[Date]),
			        all('Facts'), 
			        'Facts'[RecordSource] = "SI")
			var lastyearsameday=
			    lastdateAvailable-365
			var ifLeapYear=
			    IF(DAY(lastyearsameday)<>DAY(lastdateAvailable),
			        TRUE(),
			        FALSE())
			var lastyearsamedayLeapYear=
			    IF(ifLeapYear,
			        lastdateAvailable-366,
			        lastyearsameday)
			Return
			CALCULATE([Quoted (Open)],
			    SAMEPERIODLASTYEAR('Date'[Date]), 
			        'Date'[Date] <= lastyearsamedayLeapYear)
			```
		displayFolder: .z All Other
		lineageTag: ffd2e303-2186-4196-b0c9-430b8ce4ba7f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quoted (Open) YoY' =
			
			CALCULATE(
			    DIVIDE([Quoted (Open)],
			        [Quoted (Open) PY])-1)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: .z All Other
		lineageTag: d820fa69-10a4-4303-98c8-5925f8e9b579

	measure 'Exec Conversion rate (brought forward)' = ```
			
			SWITCH (
			    TRUE (),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "0-30", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "31-60", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -3, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "61-90", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -4, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "91-120", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -5, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -6, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -7, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -0] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            DATEADD ( 'Date'[Date], -2, MONTH ),
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -3, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -4, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -5, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -6, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -7, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			                && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "0-30", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "31-60", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "61-90", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -3, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "91-120", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -4, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -5, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -6, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -1] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            DATEADD ( 'Date'[Date], -1, MONTH ),
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -2, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -3, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -4, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -5, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -6, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			                && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "31-60", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "61-90", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "91-120", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -3, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -4, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -5, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -2] ),
			            ALL ( 'Date' )
			        )
			         && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            DATEADD ( 'Date'[Date], -0, MONTH ),
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -1, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -2, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -3, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -4, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -5, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -3] ),
			            ALL ( 'Date' )
			        )
			                && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "61-90", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -3] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "91-120", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -3] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -3, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -3] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -4, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -3] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -1, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -2, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -3, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -4, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -4] ),
			            ALL ( 'Date' )
			        )
			                && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "91-120", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -4] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -4] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -3, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -4] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -1, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -2, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -3, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -5] ),
			            ALL ( 'Date' )
			        )
			                && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "121-150", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -5] ),
			            ALL ( 'Date' )
			        )
			        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -2, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -5] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -1, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -2, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			                SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -6] ),
			            ALL ( 'Date' )
			        )
			                        && SELECTEDVALUE ( 'Days Grouping Table'[Days Grouping] ) = "151-180", CALCULATE ( [Exec Conversion rate], DATEADD ( 'Date'[Date], -1, MONTH ) ),
			    SELECTEDVALUE ( 'Date'[yyyymm] )
			        = CALCULATE (
			            MAX ( YearCalendarMonth[yyyymm -6] ),
			            ALL ( 'Date' )
			        )
			        && NOT ( HASONEVALUE ( 'Days Grouping Table'[Days Grouping] ) ),
			        CALCULATE (
			            [Exec Conversion rate],
			            FILTER (
			                ALL ( 'Days Grouping Table' ),
			                'Days Grouping Table'[Days Grouping] = "0-30"
			            )
			        )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "31-60"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "61-90"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "91-120"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "121-150"
			                )
			            )
			            + CALCULATE (
			                [Exec Conversion rate],
			                DATEADD ( 'Date'[Date], -1, MONTH ),
			                FILTER (
			                    ALL ( 'Days Grouping Table' ),
			                    'Days Grouping Table'[Days Grouping] = "151-180"
			                )
			            ),
			    [Exec Conversion rate]
			)
			
			 
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: .z All Other
		lineageTag: 97689f4e-4b66-4294-ba5c-c5985c70c124

	measure 'Exec Conversion rate' =
			
			DIVIDE(
			    [Exec Conversion rate (quote count)] + [Exec Conversion rate (quote count) (new)],
			    [Exec Conversion rate (quote count, all group days)] + [Exec Conversion rate (quote count, all group days) (New)])
		displayFolder: .z All Other
		lineageTag: 6e31677e-83ba-4f25-a1aa-1c63f084e930

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Conversion rate (quote count)' =
			
			CALCULATE(SUM(
			    LegacyQuotesTEST[Quote_Count]),
			    LegacyQuotesTEST[Exec Quote Age - Conversion] <> "Not Converted",
			    USERELATIONSHIP(LegacyQuotesTEST[Exec Quote Age - Conversion],'Days Grouping Table'[Relationship]))
		displayFolder: .z All Other
		lineageTag: b8f7267e-e66a-4d44-992d-626a99791e5d

	measure 'Exec Conversion rate (quote count) (new)' = ```
			
			CALCULATE( 
			    SUM('QuotesTEST'[Chairs]),'QuotesTEST'[Exec DaysOpen - Conversion] <> "Not Converted",
			    USERELATIONSHIP('QuotesTEST'[Exec DaysOpen - Conversion],'Days Grouping Table'[Relationship]))
			```
		displayFolder: .z All Other
		lineageTag: 4a3eea9a-ab32-4ae5-aafa-c716a59ce023

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Conversion rate (quote count, all group days)' =
			
			CALCULATE(SUM(
			    LegacyQuotesTEST[Quote_Count]),
			    USERELATIONSHIP(LegacyQuotesTEST[Exec Quote Age - Conversion],'Days Grouping Table'[Relationship]),ALL('Days Grouping Table'))
		displayFolder: .z All Other
		lineageTag: 5b3416dd-e102-4ee6-b8df-e407cc6a11a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Conversion rate (quote count, all group days) (New)' =
			
			CALCULATE(
			    SUM('QuotesTEST'[Chairs]),
			    USERELATIONSHIP('QuotesTEST'[Exec DaysOpen - Conversion], 'Days Grouping Table'[Relationship]),
			    ALL('Days Grouping Table')) * (SELECTEDVALUE('Date'[yyyymm]) > 202203)
		displayFolder: .z All Other
		lineageTag: 46f1fe8e-1c0c-4b04-a60e-be1e42852579

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Quotes Legacy (open count)' =
			
			CALCULATE(SUM(
			    LegacyQuotesTEST[Quote_Count]),
			    LegacyQuotesTEST[Order_Count] <> 1 || LegacyQuotesTEST[Exec Quote Age - Conversion] = "Not Converted",
			    USERELATIONSHIP(LegacyQuotesTEST[Exec Quote Age - Conversion],'Days Grouping Table'[Relationship]))
		displayFolder: .z All Other
		lineageTag: b55c58ce-cd88-4909-8387-1c3dc6f1655f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Quotes (open count)' = ```
			
			CALCULATE( 
			    SUM('QuotesTEST'[DaysOpen]), 
			    'QuotesTEST'[Quote Date] > 'QuotesTEST'[Quote_Date_Key],
			    'QuotesTEST'[Open-0/Converted-1] <> 1 || 'QuotesTEST'[Exec DaysOpen - Conversion] = "Not Converted",
			    USERELATIONSHIP('QuotesTEST'[Order_Date Key], 'Date'[Date]))
			```
		displayFolder: .z All Other
		lineageTag: d9b3212b-e00d-4766-8ece-cb873bcdb17e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Open Count' = ```
			
			CALCULATE(
			    [Exec Quotes (open count)],
			    'QuotesTEST'[Exec DaysOpen - Conversion] <> "Not Converted",
			    USERELATIONSHIP('QuotesTEST'[Order_Date Key], 'Date'[Date])) + 
			CALCULATE(
			    [Exec Quotes Legacy (open count)],
			    USERELATIONSHIP('LegacyQuotesTEST'[Order Date Key], 'Date'[Date]))
			```
		displayFolder: .z All Other
		lineageTag: 3c5f707b-8a7a-4b68-a8fb-a3c13bdadcf1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Exec Conversion rate (Ti)' =
			
			DIVIDE(
			    [Exec Conversion rate (quote count) (Ti)],
			    [Exec Conversion rate (quote count, all group days) (Ti)])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: .z All Other
		lineageTag: 2e936f9c-5fdc-4427-890d-26a7305f75b8

	measure 'Exec Conversion rate (quote count) (Ti)' = ```
			
			CALCULATE( 
			    SUM('TiLite_Master_QuotesData'[Count]),
			        'TiLite_Master_QuotesData'[Exec Quote Age Tilite - Conversion] <> "Not Converted",
			    USERELATIONSHIP('QuotesTEST'[Exec DaysOpen - Conversion],'Days Grouping Table'[Relationship]))
			```
		formatString: 0
		displayFolder: .z All Other
		lineageTag: 0227595b-c65e-421e-8e9e-4f94ef2e2ee0

	measure 'Exec Conversion rate (quote count, all group days) (Ti)' =
			
			CALCULATE(
			    SUM('TiLite_Master_QuotesData'[Count]),
			    USERELATIONSHIP('TiLite_Master_QuotesData'[Exec Quote Age Tilite - Conversion], 'Days Grouping Table'[Relationship]),
			    ALL('Days Grouping Table'))
		displayFolder: .z All Other
		lineageTag: 82e3e46b-728d-4acb-ab68-dce856ad82e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Power Chairs - Current Period' =
			
			CALCULATE (
			    [Total Invoiced Power Chairs],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 0e3ae600-b6ba-46bd-bdfa-a3afb2133841

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Power Chairs' =
			
			[Invoiced Power Chairs - USSC (excl Freight)] + [Invoiced Power Chairs - US Scala]
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: aabf4725-bf1d-4eff-a74a-95b87b32265c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US' =
			
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    FILTER('FactCustomerInvoice_UNION',
			        'FactCustomerInvoice_UNION'[WKCompany] = 98 &&
			        'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR"),
			    FILTER('DW DimProduct',
			        'DW DimProduct'[ProductName] <> "FREIGHT CHARGES"),
			    'Ship to customer'[Ship to internal customer] IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 07582ac3-6705-41a0-95a5-44f8e5e903b4

		changedProperty = FormatString

	measure 'Invoiced ROHO - US' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 82,
			    'DW DimProduct'[ProductLvl2Name] IN { "ROHO" },
			    'DW_DimItem'[CommissionableCheck] = "Commissionable"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 9c8460ea-6652-46dd-a31d-e586db3ba12c

		changedProperty = FormatString

	measure 'Invoiced Comfort - US' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 109,
			    'DW DimProduct'[ProductLvl2Name] = "Comfort Products"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: c7046cc1-2d15-4ac4-9b6d-855e1b8e9af3

		changedProperty = FormatString

	measure 'Invoiced SmartDrives Combined - US' =
			
			[Invoiced TiLite On-Chair - SmartDrives] +
			[Invoiced SmartDrives Off-Chair for Commissions - Total US]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 81bc0e09-0046-4ea9-b08e-45b2a15f8f59

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - Current Period' =
			
			CALCULATE (
			    [Invoiced TiLite Chairs - US],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: ef9c624f-7c36-4a50-8bc7-3962b95097d0

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced ROHO - Current Period' =
			
			CALCULATE (
			    [Invoiced ROHO - US],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 1e09a524-7536-407e-bca9-772b9022cfc0

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Comfort - Current Period' =
			
			CALCULATE (
			    [Invoiced Comfort - US],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: dea5d0bb-930b-4976-a826-f144c2ed1c7c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Combined SmartDrives - Current Period' =
			
			CALCULATE (
			    [Invoiced SmartDrives Combined - US],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 69e945f8-28fc-4d02-ab96-3441ef4ed23c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB PWC YTD' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Power Chairs], [BudgetPWC])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 2c6bc66f-fc09-4a50-9c89-86f76f58e606

		changedProperty = FormatString

	measure 'STB PWC YTD (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB PWC YTD]), "E6E6E6",
			    [STB PWC YTD] >= 1, "#9FCB9F",
			    [STB PWC YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: ef28c34b-1588-4a66-ac1e-8da75d4a09a8

		changedProperty = FormatString

	measure 'STB TiLite YTD' =
			
			DIVIDE ( [STB Actuals - Total Invoiced US TiLite Chairs], [BudgetTiLite] )
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 8c4557d3-f20f-4895-9768-5ac6f6e4cdbb

		changedProperty = FormatString

	measure 'STB TiLite YTD (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB TiLite YTD]), "E6E6E6",
			    [STB TiLite YTD] >= .90, "#9FCB9F",
			    [STB TiLite YTD] < .90, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 5558008c-65a2-4ec6-b42d-5f847276ecc2

		changedProperty = FormatString

	measure 'STB Smart Combined YTD' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Combined SmartDrives], [BudgetSD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 460a5509-375e-41d3-a43f-d994d99b6557

		changedProperty = FormatString

	measure 'STB Smart Combined YTD (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB Smart Combined YTD]), "E6E6E6",
			    [STB Smart Combined YTD] >= 1, "#9FCB9F",
			    [STB Smart Combined YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 233f4004-150c-4af5-a9c4-7dfee2c1bfc7

		changedProperty = FormatString

	measure 'STB ROHO YTD' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US ROHO], [BudgetROHO])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 61c01f1b-ec32-4a63-a6e8-a0a7f6f1aa0a

		changedProperty = FormatString

	measure 'STB ROHO YTD (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB ROHO YTD]), "E6E6E6",
			    [STB ROHO YTD] >= 1, "#9FCB9F",
			    [STB ROHO YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: fe1093b8-e760-48a8-aa74-0bd7ba73a821

		changedProperty = FormatString

	measure 'STB Comfort YTD' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Comfort], [BudgetComfort])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 5412ba74-3965-465e-86fe-43fe62bf75c5

		changedProperty = FormatString

	measure 'STB Comfort YTD (CF)' = ```
			
			    SWITCH (
			        TRUE (),
			        ISBLANK([STB Comfort YTD]), "E6E6E6",
			        [STB Comfort YTD] >= 1, "#9FCB9F",
			        [STB Comfort YTD] < 1, "#DC9999"
			    )
			```
		displayFolder: .STB
		lineageTag: be292c3c-5f59-48b9-b165-13c167ff4da9

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Total YTD' =
			
			DIVIDE ( [STB Actuals - Total Invoiced US], [BudgetTotal FY] )
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .STB
		lineageTag: 0fbc38d6-67d3-4165-aaf6-29eb3d702fb2

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Actuals - Total Invoiced US' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - US Total] +
			 [Total Invoiced - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 001c7d98-0570-40e8-8d1d-c2b0dd3548fe

		changedProperty = FormatString

	measure 'Total Invoiced - Current Period' = ```
			
			[Total Invoiced Power Chairs - Current Period] +
			[Invoiced TiLite Chairs - Current Period] +
			[Total Combined SmartDrives - Current Period] +
			[Total Invoiced ROHO - Current Period] +
			[Total Invoiced Comfort - Current Period] 
			```
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 3ba50ce7-6cbe-4469-a359-6dcc714be354

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Total YTD (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB TOTAL YTD]), "E6E6E6",
			    [STB TOTAL YTD] >= 1, "#9FCB9F",
			    [STB TOTAL YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 77f61fa0-8dca-4b1a-9d6a-90825a6c81d7

		changedProperty = FormatString

	measure 'Invoiced Returned Orders - CAN Power Parts' =
			
			CALCULATE(
			SUM('Facts'[Net price]),
			    FILTER('Date',
			        'Date'[date_int] >= 20220401),
			    FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"} &&
			       ('Facts'[Order type] <> "Chair") &&
			       ('Facts'[Order type] <> "Parts") &&
			       ('Facts'[Order type]  <> "SMRT") &&
			       ('Facts'[FinProdDesc 1] IN {"Aftermarket", "Seating & Positioning"}) &&
			       NOT ('Facts'[FinProdDesc 2] IN {"Manual AM"}) &&
			    'Facts'[Internal Customer (RO)] IN {0}
			    ))
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 600ac169-1a0c-4502-b5ad-cbf3b86580d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - CAN Power Chairs' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && 'Facts'[FinProdDesc 1]
			                IN { "Power" }
			                    && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 0698e625-4269-4b09-af0d-6af0f04c993b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - CAN Restock Fees' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && ISBLANK ( ( 'Facts'[FinProdDesc 1] ) )
			                && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: e8662436-3b8f-4833-bf38-4275d2de22aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - CAN SmartDrives' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && ( 'Facts'[FinProdDesc 1] IN { "Manual" } )
			                && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 684da63f-d9db-490b-bea4-6329cd1db56a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Returned Orders - CAN SmartDrives Parts' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && ( 'Facts'[FinProdDesc 2] IN { "Manual AM" } )
			                && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: c9d56663-f27b-42b7-a86f-0c0b8a81413d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Power Parts - CAN' =
			
			[Invoiced Power Parts - CAN] +
			[Invoiced Returned Orders - CAN Power Parts]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 3b00bdd3-75cf-419e-a9ca-f40c5b96cbdd

	measure 'Total Invoiced CAN TiLite Chairs - Current Period' =
			
			IF([BudgetTiLIte YTD]<0,0, //used 1000 when isolating only STB performance
			CALCULATE (
			    [Invoiced TiLite Chairs - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 084e4dab-a0f7-4508-90f5-a91753158bfe

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN SmartDrives - Current Period' =
			
			IF([BudgetSD YTD]<0,0, //used 1000 when isolating only STB performance
			CALCULATE (
			    [Invoiced Montreal SmartDrives - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 59fa6c9f-a134-4bbd-93d3-1c47779e4684

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN - Current Period' =
			
			[Total Invoiced CAN Power Chairs - Current Period] +
			[Total Invoiced CAN TiLite Chairs - Current Period] +
			[Total Invoiced CAN SmartDrives - Current Period] +
			[Total Invoiced CAN ROHO - Current Period] +
			[Total Invoiced CAN Comfort - Current Period] +
			[Total Invoiced CAN 3rd Party - Current Period]
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: ed2e11d6-3742-4500-8fd5-332e67a2e6be

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN Comfort - Current Period' =
			
			IF([BudgetComfort YTD]<0,0, //used 1000 when isolating only STB performance
			CALCULATE (
			    [Invoiced Montreal Comfort - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 52da7b93-4c68-44d0-92e4-d26cfa4c5e0f

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN Power Chairs - Current Period' =
			
			IF([BudgetPWC YTD]<0,0, //used 100 when isolating only STB performance
			CALCULATE (
			    [Invoiced Power Chairs - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: e945dc64-7e33-439e-83e7-9a12a9b4490c

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN ROHO - Current Period' =
			
			IF([BudgetROHO YTD]<0,0, //used 1000 when isolating only STB performance
			CALCULATE (
			    [Invoiced Montreal ROHO - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: b78405b6-2231-45de-8e46-9549bd065b46

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal TruShape - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "TruShape",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: b194c4a2-2843-420d-b1f1-4abfd547be86

	measure 'Invoiced Montreal SmartDrives - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "SmartDrives",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: b321bb99-e5bd-441c-98b5-a1e11d948d46

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced Montreal ROHO - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "ROHO",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: f2396717-c7bc-4597-8ccf-6bc452c5e7a1

	measure 'Invoiced Montreal Comfort - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "Comfort",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: dea42675-346c-4bcc-964a-5747efdb47bb

	measure 'Invoiced Montreal 3rd Party - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "3rd Party",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: a2ca2454-fc83-4b66-b65f-be4d561d30ae

	measure 'Invoiced Power Chairs - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    'Facts'[Order Type - Calculated] IN { "Chair" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: e18f4263-fc09-4b0c-bbfa-03a1a1284c04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 5306bc5b-de36-430b-ab02-db8a2fee1b86

		changedProperty = FormatString

	measure 'Total Invoiced CAN 3rd Party - Current Period' =
			
			IF([BudgetThird Party YTD]<0,0, //used 1000 when isolating only STB performance
			CALCULATE (
			    [Invoiced Montreal 3rd Party - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			))
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: f3a3dee8-44e6-4b5a-868a-f05a56643901

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced CAN TruShape - Current Period' =
			
			CALCULATE (
			    [Invoiced Montreal TruShape - CAN Raw],
			    FILTER (
			        'Date',
			        'Date'[Date] >= DATE ( 2024, 1, 1 ) -- rest of formula to be enacted when we lock down each previous quarter MAXX ( 'Master Actuals 2023', [Month] ) + 1, 1 )
			            && 'Date'[Date] <= DATE ( 2024, 12, 31 )
			    )
			)
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 42bed861-deba-4340-9bcf-9d6588de1282

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total TiLite Chairs - CAN' =
			
			[2023 Actuals CAN - Power Chair] +
			[Total Invoiced CAN Power Chairs - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: f7476644-ff21-4a50-a075-490cb45ecf01

	measure 'STB PWC YTD CAN' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced CAN Power Chairs], [BudgetPWC YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 5ceeff6e-05cf-4888-b4ea-b47e1f5345f1

		changedProperty = FormatString

	measure 'STB TiLite YTD CAN' =
			
			DIVIDE ( [STB Actuals - Total Invoiced CAN TiLite Chairs], [BudgetTiLite YTD] )
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: b51d4c5b-dcc6-49ab-af8c-57993c3a7fd3

		changedProperty = FormatString

	measure 'STB Smart Combined YTD CAN' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced CAN SmartDrives], [BudgetSD YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 68a4b773-15b7-47a4-944d-b039893ea492

		changedProperty = FormatString

	measure 'STB ROHO YTD CAN' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced CAN ROHO], [BudgetROHO YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: a4fcae89-b18a-40a8-b962-86820d45a6b2

		changedProperty = FormatString

	measure 'STB Comfort YTD CAN' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced CAN Comfort], [BudgetComfort YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: bc5c7006-5ab6-4754-a0d1-eaf5559052d9

		changedProperty = FormatString

	measure 'STB Comfort YTD CAN (CF)' = ```
			
			    SWITCH (
			        TRUE (),
			        ISBLANK([STB Comfort YTD CAN]), "E6E6E6",
			        [STB Comfort YTD] >= 1, "#9FCB9F",
			        [STB Comfort YTD] < 1, "#DC9999"
			    )
			```
		displayFolder: .STB
		lineageTag: 8560606f-5ef2-4660-b129-eab4bd86d2fb

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB PWC YTD CAN (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB PWC YTD CAN]), "E6E6E6",
			    [STB PWC YTD] >= 1, "#9FCB9F",
			    [STB PWC YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 41559b0c-90f0-45e0-9894-b5e84b3f06e8

		changedProperty = FormatString

	measure 'STB TiLite YTD CAN (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB TiLite YTD CAN]), "E6E6E6",
			    [STB TiLite YTD] >= .90, "#9FCB9F",
			    [STB TiLite YTD] < .90, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 50f2aa58-4831-4aa6-b12b-9337d8b9e522

		changedProperty = FormatString

	measure 'STB ROHO YTD CAN (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB ROHO YTD CAN]), "E6E6E6",
			    [STB ROHO YTD] >= 1, "#9FCB9F",
			    [STB ROHO YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 3a8a4dde-6b69-4421-bc97-f8d551754a23

		changedProperty = FormatString

	measure 'STB Smart Combined YTD CAN (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB Smart Combined YTD CAN]), "E6E6E6",
			    [STB Smart Combined YTD] >= 1, "#9FCB9F",
			    [STB Smart Combined YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 82bd2d82-4624-46d6-b80c-8bc191c16f1d

		changedProperty = FormatString

	measure 'STB Total YTD CAN' =
			
			DIVIDE ( [STB Actuals - Total Invoiced CAN], [BudgetTotal YTD CAN] )
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .STB
		lineageTag: 40dacb67-8094-4bbc-99ca-e0fc1f01ba9e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Total YTD CAN (CF)' =
			SWITCH (
			    TRUE (),
			    isblank([STB TOTAL YTD CAN]), "E6E6E6",
			    [STB TOTAL YTD] >= 1, "#9FCB9F",
			    [STB TOTAL YTD] < 1, "#DC9999"
			)
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: a32fc7a7-5920-4eb5-b362-becc078917f4

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - Total] +
			 [Total Invoiced CAN - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: f4eb4c01-6030-4e9b-a1a0-7971b07f89f3

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN TiLite Chairs' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - Manual] +
			 [Total Invoiced CAN TiLite Chairs - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: e5937f2b-fba0-4660-8428-bc0fa277e78d

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN ROHO' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - ROHO] +
			 [Total Invoiced CAN ROHO - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 453f9c7e-aa13-497d-9137-dc68158756e9

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN Comfort' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - Comfort] +
			 [Total Invoiced CAN Comfort - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 1ead9706-7bb6-44b0-9a87-af317b9d143b

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN SmartDrives' =
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - SmartDrive] +
			 [Total Invoiced CAN SmartDrives - Current Period]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: be113d52-994d-4402-8cd3-84809249e5f1

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced US Power Chairs' = ```
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals - Power Chair] + 
			[Total Invoiced Power Chairs - Current Period]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Sales Bonus & Commissions (US)
		lineageTag: 4ea8ea85-d09d-4709-aa60-db92b9f33d89

		changedProperty = FormatString

	measure 'STB Actuals - Total Invoiced CAN 3rd Party' = ```
			
			-- Not needed until Q1 needs to be locked down -- [2023 Actuals CAN - 3rd Party] + 
			[Total Invoiced CAN 3rd Party - Current Period]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 8cb16545-910c-46cd-a6bf-61b96306e720

		changedProperty = FormatString

	measure 'STB Third Party YTD CAN' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced CAN 3rd Party], [BudgetThird Party YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 59191796-e13f-4e7c-888d-15ccb88adf44

		changedProperty = FormatString

	measure 'Total Invoiced CAN - YTD Current Period' = ```
			
			[Invoiced Power Chairs - CAN Raw] +
			[Invoiced TiLite Chairs - CAN Raw] +
			[Invoiced Montreal SmartDrives - CAN Raw] +
			[Invoiced Montreal ROHO - CAN Raw] + 
			[Invoiced Montreal Comfort - CAN Raw] +
			[Invoiced Montreal 3rd Party - CAN Raw] +
			[Invoiced Montreal TruShape - CAN Raw]
			```
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 39d4b176-5cca-4487-8338-c5a054843b2e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Total YTD CAN - Original' =
			
			DIVIDE(
			[Total Invoiced CAN - YTD Current Period], [BudgetTotal YTD CAN - Mike K])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: bccdccfd-9def-4430-a2c3-e43034988716

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - Full Chair Order Value' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    FILTER (
			        'FactCustomerInvoice_UNION',
			        'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR"
			    )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: be9a59a5-18d6-4bb2-8d88-c7322851fc83

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - Full Order Value' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98
			    )
		displayFolder: .Sales Performance (US)\.z All Other (US)
		lineageTag: bdd7b883-c532-47a9-a7ee-df738da7ef63

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB Total YTD 2024' =
			
			DIVIDE ( [STB Actuals - Total Invoiced US], [BudgetTotal YTD] )
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .STB
		lineageTag: a19b20e8-5dea-4656-9a8e-2a9bde4b9d1d

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'STB PWC YTD 2024' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Power Chairs], [BudgetPWC YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: a8ebeedb-2b0e-44bc-a652-9318d9b51dcc

		changedProperty = FormatString

	measure 'STB Comfort YTD 2024' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Comfort], [BudgetComfort YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: d6e82cf0-04f2-4de3-b09a-8aae9f3d6ade

		changedProperty = FormatString

	measure 'STB ROHO YTD 2024' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US ROHO], [BudgetROHO YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: ed3288de-d0e8-40f5-8318-5584a8fd1a7e

		changedProperty = FormatString

	measure 'STB Smart Combined YTD 2024' =
			
			DIVIDE(
			[STB Actuals - Total Invoiced US Combined SmartDrives], [BudgetSD YTD])
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 57d202c7-5962-4e10-808b-36ad4019d9ee

		changedProperty = FormatString

	measure 'STB TiLite YTD 2024' =
			
			DIVIDE ( [STB Actuals - Total Invoiced US TiLite Chairs], [BudgetTiLite YTD] )
		formatString: 0%;-0%;0%
		displayFolder: .STB
		lineageTag: 4ccdb4c0-36a5-4f63-af11-8e605db3e83a

		changedProperty = FormatString

	measure 'Invoiced Montreal ROHO - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "ROHO",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: d9c5a988-a474-42f0-919c-c04306f3bda2

	measure 'Invoiced Montreal Comfort - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "Comfort",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 77ea3813-79c3-4d82-9549-33a9e0f6e096

	measure 'Invoiced Montreal 3rd Party - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "3rd Party",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 138f28dc-ecfc-4157-ac10-485bb3c7b59a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal TruShape - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "TruShape",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 3aa93a12-3d74-43d8-a251-05c11b9a9ae2

	measure 'Invoiced Montreal SmartDrives - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "SmartDrives",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
			//     + CALCULATE (
			//         SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			//         'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			//         FILTER (
			//             'TiLite_AttachmentReporting_Lines',
			//             'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Aluminum"
			//         ),
			//     USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			//     )
			//     + CALCULATE (
			//         SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			//         'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			//         FILTER (
			//             'TiLite_AttachmentReporting_Lines',
			//             'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Titanium"
			//         ),
			//     USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			//     )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 8ba53b8e-9665-4863-8ccf-28a6d06199d4

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '2023 Actuals CAN - 3rd Party' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "3rd Party")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: afea9f37-ddc5-43c7-8461-397da1668cd7

		changedProperty = FormatString

	measure '2023 Actuals CAN - Comfort' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "Comfort")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: bf4364f9-20af-4d33-8c6c-d236df99e2c9

		changedProperty = FormatString

	measure '2023 Actuals CAN - Manual' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "TiLite")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: fb86d837-56dd-4540-919d-590ebce16e7d

		changedProperty = FormatString

	measure '2023 Actuals CAN - Power Chair' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "Power")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 54d28509-e90a-4787-a1e2-5c1ef16b8e62

		changedProperty = FormatString

	measure '2023 Actuals CAN - ROHO' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "ROHO")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 1cfcf42c-aaea-4d7e-a29e-90de9fb8fd6f

		changedProperty = FormatString

	measure '2023 Actuals CAN - SmartDrive' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "SmartDrive")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: d736d0c9-8023-42d3-acc4-e46cc9d77bf0

		changedProperty = FormatString

	measure '2023 Actuals CAN - Total' = ```
			
			[2023 Actuals CAN - Power Chair] + 
			[2023 Actuals CAN - Manual] + 
			[2023 Actuals CAN - SmartDrive] + 
			[2023 Actuals CAN - ROHO] + 
			[2023 Actuals CAN - Comfort] +
			[2023 Actuals CAN - 3rd Party]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 24ca58a4-9c1c-423a-a26c-716dbd1bdd71

		changedProperty = FormatString

	measure '2023 Actuals CAN - TruShape' =
			
			CALCULATE(
			    SUM('Master Actuals 2023 - CAN'[Invoicing]),
			        'Master Actuals 2023 - CAN'[Attribute] = "Tru-Shape")
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Sales Commissions (CAN)
		lineageTag: 2b1f7d67-e3f1-4b5e-b73a-165969c4fe57

		changedProperty = FormatString

	measure 'Budget 2023 Canada Original' =
			
			CALCULATE(
			    SUM('Master Budget 2023 - CA'[Budget]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: bec72b2e-2d33-40b3-be3b-721ba1df9d01

		changedProperty = FormatString

	measure 'BudgetTotal YTD CAN' =
			
			[BudgetPWC YTD] +
			[BudgetTiLIte YTD] +
			[BudgetSD YTD] +
			[BudgetROHO YTD] +
			[BudgetComfort YTD] +
			[BudgetThird Party YTD]
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 8aedfbec-86b8-4fab-b913-172a40dda25e

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'BudgetTotal YTD CAN - Mike K' = ```
			
			
			// Determine Quarter based on today's date (1,2,3,4)
			VAR CurrentQuarter =
			    QUARTER( ( TODAY () ))
			
			// Calculate Previous Quarters Full Budget based on today's date (i.e. less than 3 would be Q1 & Q2)
			VAR PreviousCompletedBudgets =
			    CALCULATE([Full Year Budget - CAN Original],
			        FILTER('Date',
			            'Date'[Quarter] < CurrentQuarter
			        ))
			
			// Current Quarter Full Budget
			VAR CurrentQtrBudget =
			CALCULATE(
			    CALCULATE([Full Year Budget - CAN Original],
			        FILTER('Date',
			            'Date'[Quarter] = QUARTER(TODAY()))))
			
			// Percentage complete through this quarter based on working days (i.e. 41/63 = %)
			VAR CurrentQtr_Percent_Complete =
			DIVIDE([Current Working Day - Quarter], [Total Working Day - Quarter])
			
			// Multiply Current Quarter Budget by % Complete 
			VAR CurrentQtrBudget_to_date =
			CurrentQtr_Percent_Complete * CurrentQtrBudget
			
			RETURN
			PreviousCompletedBudgets + CurrentQtrBudget_to_date
			```
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 0b8b5975-e31d-4394-bb84-03248b94b5de

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Full Year Budget - CAN Original' =
			
			CALCULATE(
			    SUM('Master Budget 2023 - CA'[Budget]),
			        FILTER('Date',
			            'Date'[Year] = 2023))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: 89dd233a-be92-4c0b-9e05-bcf1bdc0ef32

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite Chairs - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductDescription] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 8d1f3f0e-126f-4103-b990-856961ca239c

		changedProperty = FormatString

	measure 'Total Power Chairs - CAN Raw (UR_CM)' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			    FILTER('Date',
			        'Date'[date_int] >= 20220401), 
			    FILTER('Facts',
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"} &&
			        'Facts'[Order type] IN {"Chair"} &&
			        'Facts'[FinProdDesc 1] IN {"Aftermarket", "Power"} &&
			        'Facts'[ItemNumber] <> "Freight" &&
			        NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual")),    
			    FILTER('Ship to customer',    
			        'Ship to customer'[Ship to internal customer] IN {0})
			    )
			    +
			    
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && 'Facts'[FinProdDesc 1]
			                IN { "Power" }
			                    && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 6eee42a8-65e9-4688-8f85-fdfb1af27474

	measure 'Invoiced TiLite Parts - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductDescription] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] <> "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 7bcb428c-5136-4183-981e-a2d404369f5a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal Freight- CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "Freight",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 69216bac-8d8d-4f41-be2a-a9faee256d65

	measure 'Invoiced Montreal Rebates - CAN' =
			
			CALCULATE(
			    SUM('FactCustomerInvoice_UNION'[NetAmount]),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			     FILTER('DW DimProduct',
			        'DW DimProduct'[Canada Product] = "Rebates"
			   )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.z All Other (CAN)
		lineageTag: e76f96da-badb-407f-85e3-3924703a8aba

	measure 'Invoiced Montreal Rebates - CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[ProductName] = "REBATE",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 40fb62f1-ea56-43f6-ad8d-ea4a3e50d7ec

	measure 'Invoiced TiLIte Chairs - (Demo) All Types - CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" } // CAN or Permobil Ltd Canada
			            && 'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 5b04f595-606e-423e-8132-55a7a09e4e5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) Carbon Rigid - CAN' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Carbon Rigid"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: f724258f-1ca2-4b02-b020-6e36cf06aa12

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) Carbon Rigid - CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    'Released product'[TiLite Chair Model] = "Carbon Rigid",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 09b474a9-85af-496d-8fee-76e275ec137f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) Titanium - CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    'Released product'[TiLite Chair Model] = "Titanium",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 0325a1fb-2393-4de9-9bed-062b5092e087

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) Aluminum - CAN (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    'Released product'[TiLite Chair Model] = "Aluminum",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 324a77ba-5e18-4269-87a4-9023df32a5a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - On-Chair SmartDrives - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'Sales Rep Map'[Region_] = "Canada",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 01dc2ca3-ab8f-4676-9d13-6da0bf88f238

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite Chairs - On-Chair SmartDrives - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 394395a9-9d70-4d50-beef-cfcd0aa2f030

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced Power Chairs - CAN Raw backup' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        'Date'[date_int] >= 20220401, 
			        'Facts'[Company_SK] IN {"A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D"},
			        'Facts'[Order type] IN {"Chair"},
			        'Facts'[ItemNumber] <> "Freight",
			        NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual"),    
			        'Ship to customer'[Ship to internal customer] IN {0}
			    )
			    +
			    
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    FILTER ( 'Date', 'Date'[date_int] >= 20220401 ),
			    FILTER (
			        'Facts',
			        'Facts'[Company_SK]
			            IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			                && ( 'Facts'[Order type] <> "Chair" )
			                && ( 'Facts'[Order type] <> "Parts" )
			                && ( 'Facts'[Order type] <> "SMRT" )
			                && 'Facts'[FinProdDesc 1]
			                IN { "Power" }
			                    && 'Facts'[Internal Customer (RO)] IN { 0 }
			    )
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: d644bca8-8d8a-4947-b856-39aa6a747427

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Parts - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    'Facts'[Order Type - Calculated] IN { "Parts" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: b749cfea-db9b-4237-9cf9-5186ae3a43c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power RestockFee - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }, -- CAN or Permobil Ltd Canada
			    // CONTAINSSTRING('Facts'[ItemNumber], "Restock"),
			    'Facts'[ItemNumber] = "RestockExt",
			    'Bill to customer'[Bill to internal customer] IN {0}
			    )
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: f4308a32-c1b9-444a-aaeb-993bfe76bca2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLIte Chairs - (Demo) All D365 - CAN' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" }
			            && // CAN or Permobil Ltd Canada
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 } -- used Bill to as measure is in D365 Fact Table
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: d1d36537-9f96-439f-8ff2-cd38837d559b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Montreal Freight- CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[Canada Product] = "Freight",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: cc6e4c21-c447-453e-a5c4-4d3bf6aa054d

	measure 'Invoiced Montreal Rebates - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    'DW DimProduct'[ProductName] = "REBATE",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 443470f5-d53c-44ac-a158-2e93e185a595

	measure 'Invoiced TiLite Parts - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] <> "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 7677b5dc-0c6b-42e0-bedf-6ca1d3623713

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Freight - CAN Raw (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductDescription] <> "FREIGHT CHARGES",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: a143a56e-e0e2-48a7-92d8-5408f0d4a708

		changedProperty = FormatString

	measure 'Invoiced TiLite Freight - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] = "FREIGHT CHARGES",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 788d03e7-5d5f-4c6a-8cbd-62173b2d2146

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - CAN Raw - Aluminum' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Aluminum",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 40c2c692-e3a6-4005-bdec-1cd8fefda25e

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - On-Chair SmartDrives (Aluminum) - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Aluminum",
			    'Sales Rep Map'[Region_] = "Canada",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: f8b93ae5-33b7-4f3d-ae5e-e2bf4e1e42ef

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite Chairs - On-Chair SmartDrives (Titanium) - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Titanium",
			    'Sales Rep Map'[Region_] = "Canada",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: ebf185f6-009d-4c6c-a5b2-7c013bd50317

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite Chairs - On-Chair SmartDrives (Carbon Rigid) - CAN Raw' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Carbon Rigid",
			    'Sales Rep Map'[Region_] = "Canada",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 38566aa8-064d-4b2b-ac9f-a597cc53aa05

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite Chairs - CAN Raw - Aluminum excl On-Chair SmartDrvies' = ```
			
			    [Invoiced TiLite Chairs - CAN Raw - Aluminum] - [Invoiced TiLite Chairs - On-Chair SmartDrives (Aluminum) - CAN Raw]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 6c1917e8-428f-4ab6-b275-1054b010138f

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - CAN Raw - Titanium' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Titanium",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: c12a558b-f3bc-45e2-bf00-46b64b23c0e4

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - CAN Raw - Carbon Rigid' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Carbon Rigid",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 54b40556-9de5-4762-b06b-b8d8ebcd3b8a

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - CAN Raw - Carbon Rigid excl On-Chair SmartDrvies' = ```
			
			    [Invoiced TiLite Chairs - CAN Raw - Carbon Rigid] - [Invoiced TiLite Chairs - On-Chair SmartDrives (Carbon Rigid) - CAN Raw]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: 31d2e1ce-7c42-41b3-a281-fa232737fabb

		changedProperty = FormatString

	measure 'Invoiced TiLite Chairs - CAN Raw - Titanium excl On-Chair SmartDrvies' = ```
			
			    [Invoiced TiLite Chairs - CAN Raw - Titanium] - [Invoiced TiLite Chairs - On-Chair SmartDrives (Titanium) - CAN Raw]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Sales Header Sales Rep (CAN)
		lineageTag: ec0d207a-4a4f-4d05-9d88-bb4276ce9124

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - CAN (UR_CM Facts)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    'Facts'[Order Type - Calculated] IN { "Chair" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    'Bill to customer'[Bill to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Facts'[SalesRepCode (Master Customer)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 129a03e8-6e4d-4a4e-8468-6f6247cb726c

	measure 'Invoiced Power Parts - CAN (UR_CM Facts)' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    'Facts'[Order Type - Calculated] IN { "Parts" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    'Bill to customer'[Bill to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Facts'[SalesRepCode (Master Customer)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: 3d1e3bf6-316a-4b38-8ba9-137f324c14f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - CAN Raw (UR_CM Facts)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] IN { 0 }, -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'FactCustomerInvoice_UNION'[SalesRepCode (Master Customer)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Base Measures - Customer Master Sales Rep (CAN)
		lineageTag: b1e0e626-65b4-4f0c-8037-8bfff9efa3f2

		changedProperty = FormatString

	measure 'Invoiced Montreal - Total for Dealer Commissions' =
			// all data/products excluding freight
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER ( 'DW DimProduct',
			    NOT ('DW DimProduct'[ProductCode] IN {"Freight", "Rebate"} )
			))
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 9c28e113-4889-4157-ae7d-dee524997bb7
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

	measure 'Invoiced Returned Orders - CAN Dealer Commissions' = ```
			CALCULATE(
			[Invoiced Returned Orders - CAN],
			    FILTER('Date',
			        'Date'[date_int] >= 20220401), 
			USERELATIONSHIP('Facts'[Customer_SK],'Ship to customer'[ShipToCustomer_SK]))
			```
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: ab828cca-3217-4d45-8717-f430c3304a9a
		sourceLineageTag: ad6f1ac3-c011-44f8-89f9-0044b8de5b93
		dataCategory: Uncategorized

	measure 'Total 3rd Party - CAN Dealer Commissions' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER ( 'DW DimProduct', 'DW DimProduct'[Canada Product] = "3rd Party" ),
			    FILTER (
			        'DW DimProduct',
			        NOT ( 'DW DimProduct'[ProductCode] IN { "Freight", "Rebate" } )
			    )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 5bb372e9-7a93-4dfd-813d-76d8422a949b
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

	measure 'Total 3rd Party - CAN Dealer Commissions %' =
			
			SWITCH (
			    TRUE (),
			    [Total 3rd Party - CAN Dealer Commissions] = 0
			        && [Total 3rd Party - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total 3rd Party - CAN Dealer Commissions] <> 0
			        && [Total 3rd Party - CAN Dealer Commissions PY] = 0, 1,
			    [Total 3rd Party - CAN Dealer Commissions] = 0
			        && [Total 3rd Party - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total 3rd Party - CAN Dealer Commissions],
			        [Total 3rd Party - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: e4626233-948d-4038-9830-3d604fbd6be1

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total 3rd Party - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total 3rd Party - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 9700d39e-f940-4e3d-84ed-cefa3b3600d2

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Comfort - CAN Dealer Commissions' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER (
			        'DW DimProduct',
			        'DW DimProduct'[ProductCode] IN { "850B", "850C", "850S", "850", "820" }
			    )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: d54adbe0-def7-4765-9314-cef4544a6dcc
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

	measure 'Total Comfort - CAN Dealer Commissions % ' =
			
			SWITCH (
			    TRUE (),
			    [Total Comfort - CAN Dealer Commissions] = 0
			        && [Total Comfort - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total Comfort - CAN Dealer Commissions] <> 0
			        && [Total Comfort - CAN Dealer Commissions PY] = 0, 1,
			    [Total Comfort - CAN Dealer Commissions] = 0
			        && [Total Comfort - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total Comfort - CAN Dealer Commissions],
			        [Total Comfort - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 9f3b0394-f788-4773-b72f-18a90f07615c

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Comfort - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total Comfort - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 1e108e8d-17f4-4c63-9330-c685b529df23

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions' =
			[Invoiced Montreal - Total for Dealer Commissions] +
			[Total Power Chairs - CAN Dealer Commissions] +
			[Total Power Parts - CAN Dealer Commissions] +
			[Invoiced TiLite Chairs - Canada] +
			[Invoiced TiLite Parts excl Freight - Canada]
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: ae72bcbc-2e8f-4fec-80a8-ac4d724cf0f9
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions - FY 2022 Actual' = ```
			
			
			CALCULATE(
			[Total Invoiced Canada for Dealer Commissions],  
			
			    FILTER(ALL('Date'),
			        'Date'[Year] = 2022))
			```
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 422fa7bf-fb65-4d60-869a-dbd44326eb0c

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - PY' =
			CALCULATE (
			    [Total Invoiced Canada for Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: ac761c47-7970-468a-94a8-8a2a87c35239

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q1 2022 Actual' = ```
			
			
			CALCULATE(
			[Total Invoiced Canada for Dealer Commissions],  
			
			    FILTER(ALL('Date'),
			
			        'Date'[Quarter] = 1
			        &&
			
			        'Date'[Year] = 2022))
			```
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 6d1839be-bda1-4370-80b1-afe83c88340b

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q2 2022 Actual' = ```
			
			
			CALCULATE(
			[Total Invoiced Canada for Dealer Commissions],  
			
			    FILTER(ALL('Date'),
			
			        'Date'[Quarter] = 2 &&
			
			        'Date'[Year] = 2022))
			```
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: b8e67718-8338-4d68-92f3-49caf2082154

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q2 CY - PY' =
			
			[Total Invoiced Canada for Dealer Commissions] -
			[Total Invoiced Canada for Dealer Commissions - Q2 2022 Actual]
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 538932e5-0f22-4d2d-9a79-fdde754d3793

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q2 CY - PY % copy' =
			DIVIDE (
			    [Total Invoiced Canada for Dealer Commissions - Q2 CY - PY],
			    [Total Invoiced Canada for Dealer Commissions - Q2 2022 Actual]
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 9397501a-b78b-4449-8628-edeaf320331a

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q3 2022 Actual' = ```
			
			
			CALCULATE(
			[Total Invoiced Canada for Dealer Commissions],  
			
			    FILTER(ALL('Date'),
			
			        'Date'[Quarter] = 3 &&
			
			        'Date'[Year] = 2022))
			```
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 791768ee-b3e3-444f-a57d-83536f15b5a1

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q3 CY - PY' =
			
			[Total Invoiced Canada for Dealer Commissions] -
			[Total Invoiced Canada for Dealer Commissions - Q3 2022 Actual]
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 1006fdbe-9bd5-4cbf-bf04-e6d1e299306e

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q3 CY - PY %' =
			DIVIDE (
			    [Total Invoiced Canada for Dealer Commissions - Q3 CY - PY],
			    [Total Invoiced Canada for Dealer Commissions - Q3 2022 Actual]
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 632de553-2782-47a5-8a90-7a617b74110e

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions - Q4 2022 Actual' = ```
			
			
			CALCULATE(
			[Total Invoiced Canada for Dealer Commissions],  
			
			    FILTER(ALL('Date'),
			
			        'Date'[Quarter] = 4 &&
			
			        'Date'[Year] = 2022))
			```
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 23499606-1c16-4521-9229-290641d70a4b

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions %' =
			
			DIVIDE (
			    [Total Invoiced Canada for Dealer Commissions],
			    [Total Invoiced Canada for Dealer Commissions PY]
			) - 1
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: d5070455-a224-4388-b54d-5a127d93be93

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions CY - PY' =
			
			[Total Invoiced Canada for Dealer Commissions] -
			[Total Invoiced Canada for Dealer Commissions PY]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 0e94b989-5a83-4026-b4bd-281dc258412f
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions PY' =
			CALCULATE (
			    [Total Invoiced Canada for Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: e66d1655-2fa2-4809-b4d3-08f30057709e
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions PY QTD' = CALCULATE([Total Invoiced Canada for Dealer Commissions QTD], SAMEPERIODLASTYEAR('Date'[Date]), FILTER ('DATE', 'DATE'[DATE] < TODAY()))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 03ac4a25-9735-427a-a85f-d0cdd398b97c
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions PY YTD' = TOTALYTD([Total Invoiced Canada for Dealer Commissions], SAMEPERIODLASTYEAR('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: c348259c-beac-407a-bf98-d79d14040b13
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions QTD' = CALCULATE([Total Invoiced Canada for Dealer Commissions], DATESQTD('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: db0a8edb-770e-493b-9f2c-c181a49dba2e
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions QTD v2' =
			
			calculate([Total Invoiced Canada for Dealer Commissions QTD], FILTER('DATE', 'DATE'[DATE] <= TODAY()), SAMEPERIODLASTYEAR('Date'[Date]))
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 674f04db-8e10-4ff9-b24d-8e7344341daf

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Invoiced Canada for Dealer Commissions Sales Rep Test' = ```
			CALCULATE (
			    [Total Invoiced Canada for Dealer Commissions],
			    ALL('Sales Rep Map') 
			)
			```
		formatString: $ #,##0;($ #,##0)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 47160fce-bb01-4189-ac2c-86970105b8a4
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Invoiced Canada for Dealer Commissions YTD' = TOTALYTD([Total Invoiced Canada for Dealer Commissions], ('Date'[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 3431860f-38d6-4c80-b6b6-fe5a56716280
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Power - CAN Dealer Commission %' =
			
			SWITCH (
			    TRUE (),
			    [Total Power - CAN Dealer Commissions] = 0
			        && [Total Power - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total Power - CAN Dealer Commissions] <> 0
			        && [Total Power - CAN Dealer Commissions PY] = 0, 1,
			    [Total Power - CAN Dealer Commissions] = 0
			        && [Total Power - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total Power - CAN Dealer Commissions],
			        [Total Power - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: bcb497ee-0b61-4ef0-874f-24e1f4d91ae0

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Power - CAN Dealer Commissions' =
			[Total Power Chairs - CAN Dealer Commissions] +
			[Total Power Parts - CAN Dealer Commissions]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 30b02248-dea7-4c7f-a0f1-a9fbf5c2a996
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Power - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total Power - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 9cf45254-f520-476c-bba2-f7e5e270ba7d

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Power Chairs - CAN Dealer Commissions' =
			[Invoiced Power Chairs - Scala CAN] +
			[Invoiced Power Chairs - CAN] +
			[Invoiced Returned Orders - CAN Dealer Commissions]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: daaa2dd4-ff8b-4508-b1a3-d88f09d2ad76
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total Power Chairs - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total Power Chairs - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: a2436046-b151-40d1-9b4a-562c0b6370cd

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Power Parts - CAN Dealer Commissions' = ```
			[Invoiced Power Parts - Scala CAN] +
			[Invoiced Power Parts - CAN] 
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: fb298479-c475-44f8-a677-0026b0cc3712
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

		changedProperty = Name

	measure 'Total ROHO - CAN Dealer Commissions' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER ( 'DW DimProduct', 'DW DimProduct'[ProductCode] IN {"RC1", "RO1", "RM1"} )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: ef5240ad-c6c8-40dd-98d9-088f58ac5758
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

	measure 'Total ROHO - CAN Dealer Commissions %' =
			
			SWITCH (
			    TRUE (),
			    [Total ROHO - CAN Dealer Commissions] = 0
			        && [Total ROHO - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total ROHO - CAN Dealer Commissions] <> 0
			        && [Total ROHO - CAN Dealer Commissions PY] = 0, 1,
			    [Total ROHO - CAN Dealer Commissions] = 0
			        && [Total ROHO - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total ROHO - CAN Dealer Commissions],
			        [Total ROHO - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: afbc5f73-f848-48f5-9664-2e397a4d29fe

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total ROHO - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total ROHO - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 89e9d9fa-30ea-4dc0-b09d-e3db65dbe8cc

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total ROHO Units - CAN Dealer Commissions' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[OrderQuantity] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER ( 'DW DimProduct', 'DW DimProduct'[ProductCode] IN {"RC1", "RO1", "RM1"} )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: c4b0b04c-1274-492b-845f-5f251f84ed1a
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

	measure 'Total SmartDrives - CAN Dealer Commission' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 104,
			    FILTER ( 'DW DimProduct', 'DW DimProduct'[ProductCode] = "830" )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: c2c7691e-63cf-4939-a3ae-e265cd9c8f53
		sourceLineageTag: 804e27fe-7e3c-426d-bee5-88d9cb634edb
		dataCategory: Uncategorized

		changedProperty = Name

	measure 'Total SmartDrives - CAN Dealer Commissions %' =
			
			SWITCH (
			    TRUE (),
			    [Total SmartDrives - CAN Dealer Commission] = 0
			        && [Total SmartDrives - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total SmartDrives - CAN Dealer Commission] <> 0
			        && [Total SmartDrives - CAN Dealer Commissions PY] = 0, 1,
			    [Total SmartDrives - CAN Dealer Commission] = 0
			        && [Total SmartDrives - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total SmartDrives - CAN Dealer Commission],
			        [Total SmartDrives - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 148a3741-8b66-459a-acc1-70354ff19b69

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total SmartDrives - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total SmartDrives - CAN Dealer Commission],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: $ #,##0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 6009742a-95b9-4b00-94b3-dc1ad3bbbd84

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total TiLite - CAN Dealer Commissions' =
			[Invoiced TiLite Chairs - Canada] +
			[Invoiced TiLite Parts excl Freight - Canada]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 5e9e2953-a255-4b23-b722-673522188004
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Total TiLite - CAN Dealer Commissions %' =
			
			SWITCH (
			    TRUE (),
			    [Total TiLite - CAN Dealer Commissions] = 0
			        && [Total TiLite - CAN Dealer Commissions PY] = 0, BLANK (),
			    [Total TiLite - CAN Dealer Commissions] <> 0
			        && [Total TiLite - CAN Dealer Commissions PY] = 0, 1,
			    [Total TiLite - CAN Dealer Commissions] = 0
			        && [Total TiLite - CAN Dealer Commissions PY] <> 0, -1,
			    DIVIDE (
			        [Total TiLite - CAN Dealer Commissions],
			        [Total TiLite - CAN Dealer Commissions PY]
			    ) - 1
			)
		formatString: #,##0 %;(#,##0 %)
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 79fae595-b3aa-4a4a-a6ba-c46f31bbd1fa

		changedProperty = Name

		changedProperty = DisplayFolder

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total TiLite - CAN Dealer Commissions PY' =
			
			CALCULATE (
			    [Total TiLite - CAN Dealer Commissions],
			    SAMEPERIODLASTYEAR ( 'Date'[Date] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: 0ef20ee6-c959-4547-880d-1d8803b9d50b
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Invoiced TiLite Chairs - Canada' =
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductLvl2Name] = "TiLite",
			    'Ship to customer'[MasterCountry] = "Canada",
			    'Ship to customer'[Ship to internal customer] = 0
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: e7589f99-6c5f-4dfc-b289-af14c70296dc
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Invoiced TiLite Parts excl Freight - Canada' = ```
			CALCULATE(
			    SUM('FactCustomerInvoice_UNION'[NetAmount]),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    FILTER('DW DimProduct',
			        'DW DimProduct'[ProductLvl2Name] <> "TiLite"),
			                                FILTER('Ship to customer', 
			    'Ship to customer'[MasterCountry] = "Canada"),
			            FILTER('DW DimProduct',
			        'DW DimProduct'[ProductDescription] <> "FREIGHT CHARGES"
			    )
			)
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (CAN)\.Dealer Statements & Rebates (CAN)
		lineageTag: e13cd3c6-1c00-4ba4-9d9b-d1bf4f8a2e84
		sourceLineageTag: 7bbdc681-c99f-4f9c-9322-eda7c8f72bf8
		dataCategory: Uncategorized

	measure 'Invoiced Power Chairs - US New' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "A1CC37EFDDBBDA8BAA87443BAE04F2CA6C0BFB6D" },
			    'Facts'[Order Type - Calculated] IN { "Chair" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 91657f15-c499-468f-b4ef-029911babd23

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced Power Chairs - USSC (excl Freight)- Old' = ```
			
			CALCULATE(
			    SUM('Facts'[Net price]),
			        FILTER('Facts',
			        'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			        'Facts'[Order type] IN {"Chair"} &&
			    'Facts'[FinProdDesc 1] IN {"Aftermarket", "Power"} &&
			    'Facts'[ItemNumber] <> "Freight" &&
			    NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Manual")),    
			    FILTER('Ship to customer',    
			    'Ship to customer'[Ship to internal customer] IN {0}    ))
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 87f1e246-e4da-4ad4-a0d7-748148ec4b57

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - USSC excl Freight (UR_CM)' = ```
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" },
			    -- USSC
			    'Facts'[Order Type - Calculated] IN { "Chair" },
			    NOT CONTAINSSTRING ( 'Facts'[FinProdDesc 1], "Manual" ),
			    -- expect this to filter out Manual Demos sales which should be added to TiLite
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    -- expect filter to exclude all Frieght item numbers and RestockExt item numbers typically for restock fees on Returned Orders
			    'Bill to customer'[Bill to internal customer]
			        IN {
			            0
			        }, -- using Bill to instead of Ship to as often Returned Orders don't have a Ship to customer number
			        -- means any part sold on a Chair Order Type will be measured as Chair for performance
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Facts'[SalesRepCode (Master Customer)] )
			)
			        
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 4fdcf755-ee76-4359-a68c-4a1e7c4d74e8

		changedProperty = FormatString

	measure 'Invoiced Power Chairs - US (UR_CM)' =
			
			[Invoiced Power Chairs - USSC excl Freight (UR_CM)] + [Invoiced Power Chairs - US Scala]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 621b79aa-ee66-4ce1-970c-e4619893fa18

		changedProperty = FormatString

	measure 'Invoiced TiLIte Chairs - (Demo) USSC Carbon Rigid' =
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Facts'[Company_SK]
			        IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" }
			            && // USSC
			        'Facts'[Order type]
			            IN { "Chair" }
			                && 'Facts'[FinProdDesc 1] IN { "Manual" },
			    'Bill to customer'[Bill to internal customer] IN { 0 }, -- used Bill to as measure is in D365 Fact Table
			    'Released product'[TiLite Chair Model] = "Carbon Rigid"
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 08ef3c22-3aa9-4c6c-877c-988ed9e0d112

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US Carbon Rigid' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'FactCustomerInvoice_UNION'[TiLite Chair Type] = "Carbon Rigid",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: 18c44cb2-870f-4361-a2fe-81e23b5ee1d0

		changedProperty = FormatString

	measure 'Invoiced TiLite On-Chair - SmartDrives Carbon Rigid' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Carbon Rigid",
			    'Ship to customer'[Ship to internal customer]
			        IN { 0 } -- intentionally used Ship to in order to match Canada model that tied out
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: ffcbc721-28e3-4c4f-b099-b0ae1f210980

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US Carbon Rigid excl On-Chair SD' = ```
			
			    [Invoiced TiLite Chairs - US Carbon Rigid] - [Invoiced TiLite On-Chair - SmartDrives Carbon Rigid]
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Sales Header Sales Rep (US)
		lineageTag: ae26fec8-100a-4419-9f78-64e6cb8ea2a0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invoiced TiLite Chairs - US (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'FactCustomerInvoice_UNION'[NetAmount] ),
			    'FactCustomerInvoice_UNION'[WKCompany] = 98,
			    'DW DimProduct'[ProductName] <> "FREIGHT CHARGES",
			    'FactCustomerInvoice_UNION'[TiLite Order Type] = "CHAIR",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    -- intentionally used Ship to in order to tie to Canada Dealer Commissions
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: d2c5ea0b-6e6c-4db3-b180-5021ee31b64f

		changedProperty = FormatString

	measure 'Invoiced TiLite On-Chair - SmartDrives (UR_CM)' =
			
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'Ship to customer'[Ship to internal customer] IN { 0 },
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 3ce416ca-7d3e-4181-8a31-b580daa56b2a

		changedProperty = FormatString

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Invoiced TiLite On-Chair - SmartDrives Carbon Rigid(UR_CM)' =
			CALCULATE (
			    SUM ( 'TiLite_AttachmentReporting_Lines'[NetSalesValue] ),
			    'TiLite_AttachmentReporting_Lines'[AttachmentType] = "SmartDrive",
			    'TiLite_AttachmentReporting_Lines'[TiLite Chair Model] = "Carbon Rigid",
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Ship to customer'[Sales Rep (Customer Master)] )
			)
		formatString: 0.00
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 477113b0-7beb-494d-91c7-c7eb95f3c41e

	measure 'Invoiced SmartDrives Off-Chair for Commissions - USSC (UR_CM)' = ```
			
			// CALCULATE(
			//     SUM('Facts'[Net price]),
			//         FILTER('Facts',
			//         'Facts'[Company_SK] IN {"DBF107EA99A53AFD092321B962232EFB81FF9297"} && // USSC
			//         'Facts'[Initiative] IN {"SmartDrive Commission Identification"} && // Excel file with each part # for sales credit
			//         'Facts'[Order type] IN {"SMRT", "Parts"} &&
			//         'Facts'[FinProdDesc 1] IN {"Aftermarket", "Manual", "Power Assisted Device"} &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Power") &&
			//         NOT CONTAINSSTRING('Facts'[FinProdDesc 2], "Services")
			//     )
			// )
			
			CALCULATE (
			    SUM ( 'Facts'[Net price] ),
			    'Date'[date_int] >= 20220401,
			    'Facts'[Company_SK] IN { "DBF107EA99A53AFD092321B962232EFB81FF9297" },-- USSC
			    'Facts'[Initiative] IN {"SmartDrive Commission Identification"}, // Excel file with each part # for sales credit
			    'Facts'[Order Type - Calculated] IN { "SMRT" },
			    NOT 'Facts'[ItemNumber] IN { "Freight", "RestockExt" },
			    -- expect filter to exclude all Frieght item numbers and RestockExt item numbers typically for restock fees on Returned Orders
			    'Bill to customer'[Bill to internal customer]IN {0}, -- using Bill to instead of Ship to as often Returned Orders don't have a Ship to customer number
			    USERELATIONSHIP ( 'Sales Rep Map'[Rep], 'Facts'[SalesRepCode (Master Customer)] )
			)
			        
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: .Sales Performance (US)\.Base Measures - Customer Master Sales Rep (US)
		lineageTag: 44d950c1-b916-45a8-98d8-a68d08eb2a9e

		changedProperty = FormatString

	measure Example =
			
			BLANK()
		displayFolder: .Sales Performance (US)
		lineageTag: 3687a9d4-71a6-4380-b6c6-30a64f44e833

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '3 Profile Measures-43eb16fc-ce03-4c16-b5fc-3fca67495e96' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

