table 'CAN British Columbia Transition'
	lineageTag: b3d7ea29-1253-4399-9776-c7a097286749

	column Dealer
		dataType: string
		lineageTag: 087eea17-a0ae-4d29-8e12-3e9cfd517438
		summarizeBy: none
		sourceColumn: Dealer

		annotation SummarizationSetBy = Automatic

	column Permobil
		dataType: string
		lineageTag: 37fd624a-8632-4658-ae8f-eb35fbbf07b5
		summarizeBy: none
		sourceColumn: Permobil

		annotation SummarizationSetBy = Automatic

	column TiLite
		dataType: string
		lineageTag: 370b5285-d7a4-4b3d-9b59-5d7e5c3b2c49
		summarizeBy: none
		sourceColumn: TiLite

		annotation SummarizationSetBy = Automatic

	partition 'CAN British Columbia Transition-e41e9485-4cd2-4b7b-85d6-3ecbdd8842b0' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZLLasMwFER/RWidgGQ7crUOoYGQYih042YhOyIVkXRTWabk7ys/5Dzowt3NYnTuzKCyxIWTRrUG7aFSWvkrKhwc29o3eIEpIQljWVA5CZJyfFiUeAfgpRVXtAbdmkoJtAUj0V4eVS002ny36mKk9WiJ1k7YygGcBxihOethWdCrf8NE47U8CTcmy3mXrKf09i+hHCpex1NJSuKpJO1Nb8IrsAH6LoOyJ/TZdv1uzZd3rxM+tiYpnft6J4wGuDQT42VabnaCD+ks2EhgMQVl+ewUUsOPFXFxTqYQZNgKOsQfRhobk+zRWIT9Ve1vscKg0bp6Yj5MkPBsgKZhxifofdHwyeJxmoepDr8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Dealer = _t, Permobil = _t, TiLite = _t])
				in
				    Source

	annotation PBI_ResultType = Table

